import type { Product } from '@/types';

interface CustomerSegment {
    type: 'budget' | 'regular' | 'premium' | 'health_conscious' | 'convenience' | 'family';
    basketSize: { min: number; max: number };
    preferredCategories: string[];
    frequencyWeight: number;
}

interface TimePattern {
    hour: number;
    dayOfWeek: number; // 0-6 (Sunday-Saturday)
    season: 'spring' | 'summer' | 'fall' | 'winter';
}

// Comprehensive product catalog with detailed product information
export const PRODUCT_CATALOG: Product[] = [
    // Fresh Produce - Fruits (IDs 1-10)
    {
        id: 1,
        name: 'Organic Gala Apples',
        price: 3.99,
        emoji: '🍎',
        category: 'fruits',
        brand: 'Fresh Farms',
        description: 'Crisp and sweet organic Gala apples, perfect for snacking or baking.',
        specifications: { 'Type': 'Gala', 'Organic': 'Yes', 'Origin': 'Washington State' },
        dimensions: { length: 8, width: 8, height: 8, unit: 'cm' },
        weight: { value: 150, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400'],
        rating: 4.5,
        reviewCount: 128,
        inStock: true,
        tags: ['organic', 'fresh', 'snack', 'baking'],
        sku: 'FF-APP-GALA-001',
        availability: 'in_stock'
    },
    {
        id: 2,
        name: 'Fresh Bananas',
        price: 0.59,
        emoji: '🍌',
        category: 'fruits',
        brand: 'Tropical Fresh',
        description: 'Ripe yellow bananas with perfect texture for smoothies, baking, or eating fresh.',
        specifications: { 'Ripeness': 'Ready to eat', 'Origin': 'Ecuador' },
        dimensions: { length: 18, width: 4, height: 4, unit: 'cm' },
        weight: { value: 120, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1571771019784-3ff35f4f4277?w=400'],
        rating: 4.3,
        reviewCount: 256,
        inStock: true,
        tags: ['fresh', 'potassium', 'smoothie', 'snack'],
        sku: 'TF-BAN-001',
        availability: 'in_stock'
    },
    {
        id: 3,
        name: 'Navel Oranges',
        price: 4.49,
        emoji: '🍊',
        category: 'fruits',
        brand: 'Citrus Valley',
        description: 'Juicy seedless navel oranges, perfect for fresh juice or eating.',
        specifications: { 'Type': 'Navel', 'Seedless': 'Yes', 'Origin': 'California' },
        dimensions: { length: 8, width: 8, height: 8, unit: 'cm' },
        weight: { value: 200, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1557800636-894a64c1696f?w=400'],
        rating: 4.4,
        reviewCount: 89,
        inStock: true,
        tags: ['vitamin-c', 'juice', 'fresh', 'citrus'],
        sku: 'CV-ORA-NAV-001',
        availability: 'in_stock'
    },
    {
        id: 4,
        name: 'Red Seedless Grapes',
        price: 3.99,
        emoji: '🍇',
        category: 'fruits',
        brand: 'Vineyard Fresh',
        description: 'Sweet and juicy red seedless grapes, perfect for snacking or fruit salads.',
        specifications: { 'Type': 'Red Seedless', 'Origin': 'Chile' },
        dimensions: { length: 15, width: 10, height: 5, unit: 'cm' },
        weight: { value: 500, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1537640538966-79f36943f303?w=400'],
        rating: 4.6,
        reviewCount: 167,
        inStock: true,
        tags: ['seedless', 'sweet', 'snack', 'salad'],
        sku: 'VF-GRP-RED-001',
        availability: 'in_stock'
    },
    {
        id: 5,
        name: 'Fresh Strawberries',
        price: 4.99,
        emoji: '🍓',
        category: 'fruits',
        brand: 'Berry Best',
        description: 'Plump, juicy strawberries bursting with flavor. Perfect for desserts.',
        specifications: { 'Type': 'Fresh', 'Origin': 'California' },
        dimensions: { length: 12, width: 8, height: 4, unit: 'cm' },
        weight: { value: 454, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?w=400'],
        rating: 4.7,
        reviewCount: 203,
        inStock: true,
        tags: ['juicy', 'sweet', 'dessert', 'smoothie'],
        sku: 'BB-STR-001',
        availability: 'in_stock'
    },
    {
        id: 21,
        name: 'Green Kiwi',
        price: 0.99,
        emoji: '🥝',
        category: 'fruits',
        brand: 'Zespri',
        description: 'Tangy and sweet green kiwis packed with Vitamin C.',
        specifications: { 'Type': 'Green', 'Origin': 'New Zealand' },
        dimensions: { length: 6, width: 4, height: 4, unit: 'cm' },
        weight: { value: 100, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1585059895524-72359e06138a?w=400'],
        rating: 4.5,
        reviewCount: 85,
        inStock: true,
        tags: ['vitamin-c', 'tropical', 'snack'],
        sku: 'ZS-KIWI-GRN-001',
        availability: 'in_stock'
    },
    {
        id: 22,
        name: 'Fresh Blueberries',
        price: 3.99,
        emoji: '🫐',
        category: 'fruits',
        brand: 'Berry Best',
        description: 'Antioxidant-rich blueberries, perfect for yogurt and baking.',
        specifications: { 'Type': 'Highbush', 'Origin': 'Michigan' },
        dimensions: { length: 10, width: 10, height: 4, unit: 'cm' },
        weight: { value: 170, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400'],
        rating: 4.8,
        reviewCount: 312,
        inStock: true,
        tags: ['antioxidant', 'superfood', 'baking'],
        sku: 'BB-BLU-001',
        availability: 'in_stock'
    },
    {
        id: 23,
        name: 'Honeycrisp Apples',
        price: 2.99,
        emoji: '🍎',
        category: 'fruits',
        brand: 'Orchard Select',
        description: 'Premium Honeycrisp apples with explosive crunch and sweet-tart flavor.',
        specifications: { 'Type': 'Honeycrisp', 'Origin': 'Minnesota' },
        dimensions: { length: 9, width: 9, height: 9, unit: 'cm' },
        weight: { value: 220, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1619546813926-a78fa6372cd2?w=400'],
        rating: 4.9,
        reviewCount: 450,
        inStock: true,
        tags: ['premium', 'crunchy', 'sweet'],
        sku: 'OS-APP-HON-001',
        availability: 'in_stock'
    },
    {
        id: 24,
        name: 'Fresh Pineapple',
        price: 3.49,
        emoji: '🍍',
        category: 'fruits',
        brand: 'Tropical Gold',
        description: 'Sweet golden pineapple, ripe and ready to cut.',
        specifications: { 'Type': 'Gold', 'Origin': 'Costa Rica' },
        dimensions: { length: 30, width: 15, height: 15, unit: 'cm' },
        weight: { value: 1500, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=400'],
        rating: 4.6,
        reviewCount: 120,
        inStock: true,
        tags: ['tropical', 'sweet', 'fresh'],
        sku: 'TG-PIN-001',
        availability: 'in_stock'
    },
    {
        id: 25,
        name: 'Watermelon',
        price: 5.99,
        emoji: '🍉',
        category: 'fruits',
        brand: 'Summer Sweet',
        description: 'Seedless mini watermelon, perfect size for the fridge.',
        specifications: { 'Type': 'Mini Seedless', 'Origin': 'Florida' },
        dimensions: { length: 20, width: 20, height: 20, unit: 'cm' },
        weight: { value: 2500, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400'],
        rating: 4.7,
        reviewCount: 180,
        inStock: true,
        tags: ['summer', 'hydrating', 'sweet'],
        sku: 'SS-WAT-MIN-001',
        availability: 'in_stock'
    },

    // Fresh Produce - Vegetables (IDs 6-8, 26-32)
    {
        id: 6,
        name: 'Organic Romaine Lettuce',
        price: 2.49,
        emoji: '🥬',
        category: 'vegetables',
        brand: 'Green Valley Organics',
        description: 'Crisp organic romaine lettuce, perfect for salads and sandwiches.',
        specifications: { 'Type': 'Romaine', 'Organic': 'Yes' },
        dimensions: { length: 25, width: 12, height: 8, unit: 'cm' },
        weight: { value: 300, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1556801712-76c8e162dca5?w=400'],
        rating: 4.2,
        reviewCount: 145,
        inStock: true,
        tags: ['organic', 'salad', 'crisp'],
        sku: 'GVO-LET-ROM-001',
        availability: 'in_stock'
    },
    {
        id: 7,
        name: 'Vine-Ripened Tomatoes',
        price: 3.99,
        emoji: '🍅',
        category: 'vegetables',
        brand: 'Sunshine Farms',
        description: 'Juicy vine-ripened tomatoes with rich flavor.',
        specifications: { 'Type': 'Vine-ripened', 'Origin': 'Florida' },
        dimensions: { length: 6, width: 6, height: 6, unit: 'cm' },
        weight: { value: 150, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1546470427-e9b3a5db3c11?w=400'],
        rating: 4.4,
        reviewCount: 178,
        inStock: true,
        tags: ['juicy', 'ripe', 'salad', 'sauce'],
        sku: 'SF-TOM-VINE-001',
        availability: 'in_stock'
    },
    {
        id: 8,
        name: 'Baby Carrots',
        price: 1.99,
        emoji: '🥕',
        category: 'vegetables',
        brand: 'Crunchy Farms',
        description: 'Sweet and crunchy baby carrots, pre-washed and ready to eat.',
        specifications: { 'Type': 'Baby carrots', 'Pre-washed': 'Yes' },
        dimensions: { length: 8, width: 2, height: 2, unit: 'cm' },
        weight: { value: 340, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1582515073490-39981397c445?w=400'],
        rating: 4.3,
        reviewCount: 134,
        inStock: true,
        tags: ['crunchy', 'sweet', 'snack'],
        sku: 'CF-CAR-BABY-001',
        availability: 'in_stock'
    },
    {
        id: 26,
        name: 'Fresh Broccoli Crowns',
        price: 2.29,
        emoji: '🥦',
        category: 'vegetables',
        brand: 'Green Giant',
        description: 'Fresh broccoli crowns, rich in vitamins and fiber.',
        specifications: { 'Type': 'Crowns', 'Origin': 'California' },
        dimensions: { length: 15, width: 15, height: 15, unit: 'cm' },
        weight: { value: 400, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=400'],
        rating: 4.5,
        reviewCount: 98,
        inStock: true,
        tags: ['healthy', 'vitamin-c', 'fiber'],
        sku: 'GG-BRO-CRN-001',
        availability: 'in_stock'
    },
    {
        id: 27,
        name: 'Red Bell Peppers',
        price: 1.49,
        emoji: '🫑',
        category: 'vegetables',
        brand: 'Color Crisp',
        description: 'Sweet and crunchy red bell peppers, great for stir-fry or salads.',
        specifications: { 'Type': 'Red Bell', 'Origin': 'Mexico' },
        dimensions: { length: 10, width: 8, height: 8, unit: 'cm' },
        weight: { value: 180, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1563565375-f3fdf5d6c465?w=400'],
        rating: 4.6,
        reviewCount: 112,
        inStock: true,
        tags: ['sweet', 'crunchy', 'vitamin-c'],
        sku: 'CC-PEP-RED-001',
        availability: 'in_stock'
    },
    {
        id: 28,
        name: 'Yellow Onions',
        price: 2.99,
        emoji: '🧅',
        category: 'vegetables',
        brand: 'Savory Roots',
        description: 'Versatile yellow onions, a staple for cooking.',
        specifications: { 'Type': 'Yellow', 'Pack Size': '3 lb bag' },
        dimensions: { length: 20, width: 15, height: 10, unit: 'cm' },
        weight: { value: 1360, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1620574387735-3624d75b2dbc?w=400'],
        rating: 4.3,
        reviewCount: 88,
        inStock: true,
        tags: ['cooking', 'staple', 'flavor'],
        sku: 'SR-ONI-YEL-001',
        availability: 'in_stock'
    },
    {
        id: 29,
        name: 'Russet Potatoes',
        price: 4.99,
        emoji: '🥔',
        category: 'vegetables',
        brand: 'Idaho Best',
        description: 'Classic Russet potatoes, perfect for baking or mashing.',
        specifications: { 'Type': 'Russet', 'Pack Size': '5 lb bag' },
        dimensions: { length: 30, width: 20, height: 15, unit: 'cm' },
        weight: { value: 2268, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1518977676651-b53c82a6ade8?w=400'],
        rating: 4.5,
        reviewCount: 156,
        inStock: true,
        tags: ['baking', 'mashing', 'staple'],
        sku: 'IB-POT-RUS-001',
        availability: 'in_stock'
    },
    {
        id: 30,
        name: 'Fresh Spinach',
        price: 2.99,
        emoji: '🍃',
        category: 'vegetables',
        brand: 'Popeye Greens',
        description: 'Pre-washed baby spinach leaves, ready for salads or cooking.',
        specifications: { 'Type': 'Baby Spinach', 'Pre-washed': 'Yes' },
        dimensions: { length: 25, width: 20, height: 8, unit: 'cm' },
        weight: { value: 284, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400'],
        rating: 4.4,
        reviewCount: 132,
        inStock: true,
        tags: ['healthy', 'iron', 'salad'],
        sku: 'PG-SPI-BAB-001',
        availability: 'in_stock'
    },
    {
        id: 31,
        name: 'Cucumber',
        price: 0.99,
        emoji: '🥒',
        category: 'vegetables',
        brand: 'Cool Crisp',
        description: 'Refreshing English cucumber, seedless and thin-skinned.',
        specifications: { 'Type': 'English', 'Seedless': 'Yes' },
        dimensions: { length: 30, width: 4, height: 4, unit: 'cm' },
        weight: { value: 300, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=400'],
        rating: 4.5,
        reviewCount: 95,
        inStock: true,
        tags: ['refreshing', 'salad', 'crunchy'],
        sku: 'CC-CUC-ENG-001',
        availability: 'in_stock'
    },
    {
        id: 32,
        name: 'Avocado',
        price: 1.99,
        emoji: '🥑',
        category: 'vegetables',
        brand: 'Green Gold',
        description: 'Creamy Hass avocado, rich in healthy fats.',
        specifications: { 'Type': 'Hass', 'Origin': 'Mexico' },
        dimensions: { length: 10, width: 7, height: 7, unit: 'cm' },
        weight: { value: 200, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1523049673856-64917be304c5?w=400'],
        rating: 4.7,
        reviewCount: 210,
        inStock: true,
        tags: ['healthy-fats', 'creamy', 'superfood'],
        sku: 'GG-AVO-HAS-001',
        availability: 'in_stock'
    },

    // Dairy (IDs 9-10, 33-38)
    {
        id: 9,
        name: 'Whole Milk',
        price: 3.49,
        emoji: '🥛',
        category: 'dairy',
        brand: 'Dairy Pure',
        description: 'Fresh whole milk from local dairy farms.',
        specifications: { 'Type': 'Whole Milk', 'Fat Content': '3.25%' },
        dimensions: { length: 10, width: 10, height: 25, unit: 'cm' },
        weight: { value: 1893, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400'],
        rating: 4.5,
        reviewCount: 89,
        inStock: true,
        tags: ['fresh', 'creamy', 'local'],
        sku: 'DP-MIL-WHO-001',
        availability: 'in_stock'
    },
    {
        id: 10,
        name: 'Greek Yogurt',
        price: 4.99,
        emoji: '🥣',
        category: 'dairy',
        brand: 'Mountain View Dairy',
        description: 'Thick and creamy Greek yogurt, strained for extra protein.',
        specifications: { 'Type': 'Greek', 'Fat Content': '2%' },
        dimensions: { length: 8, width: 8, height: 12, unit: 'cm' },
        weight: { value: 150, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400'],
        rating: 4.6,
        reviewCount: 156,
        inStock: true,
        tags: ['protein', 'creamy', 'greek'],
        sku: 'MVD-YOG-GRK-001',
        availability: 'in_stock'
    },
    {
        id: 33,
        name: 'Cheddar Cheese Block',
        price: 5.99,
        emoji: '🧀',
        category: 'dairy',
        brand: 'Tillamook',
        description: 'Sharp cheddar cheese block, aged for 9 months.',
        specifications: { 'Type': 'Sharp Cheddar', 'Aged': '9 months' },
        dimensions: { length: 15, width: 8, height: 5, unit: 'cm' },
        weight: { value: 454, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?w=400'],
        rating: 4.8,
        reviewCount: 220,
        inStock: true,
        tags: ['cheese', 'sharp', 'aged'],
        sku: 'TL-CHE-SHA-001',
        availability: 'in_stock'
    },
    {
        id: 34,
        name: 'Unsalted Butter',
        price: 4.49,
        emoji: '🧈',
        category: 'dairy',
        brand: 'Land O Lakes',
        description: 'Sweet cream unsalted butter, perfect for baking.',
        specifications: { 'Type': 'Unsalted', 'Cream': 'Sweet' },
        dimensions: { length: 12, width: 6, height: 6, unit: 'cm' },
        weight: { value: 454, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400'],
        rating: 4.7,
        reviewCount: 185,
        inStock: true,
        tags: ['baking', 'creamy', 'butter'],
        sku: 'LL-BUT-UNS-001',
        availability: 'in_stock'
    },
    {
        id: 35,
        name: 'Large Eggs',
        price: 3.99,
        emoji: '🥚',
        category: 'dairy',
        brand: 'Eggland\'s Best',
        description: 'Grade A large white eggs, rich in vitamins.',
        specifications: { 'Grade': 'A', 'Size': 'Large', 'Count': '12' },
        dimensions: { length: 30, width: 10, height: 7, unit: 'cm' },
        weight: { value: 680, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400'],
        rating: 4.6,
        reviewCount: 310,
        inStock: true,
        tags: ['protein', 'breakfast', 'baking'],
        sku: 'EB-EGG-LRG-001',
        availability: 'in_stock'
    },
    {
        id: 36,
        name: 'Heavy Whipping Cream',
        price: 4.29,
        emoji: '🥛',
        category: 'dairy',
        brand: 'Horizon Organic',
        description: 'Rich heavy whipping cream for desserts and cooking.',
        specifications: { 'Type': 'Heavy Cream', 'Organic': 'Yes' },
        dimensions: { length: 7, width: 7, height: 15, unit: 'cm' },
        weight: { value: 473, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=400'],
        rating: 4.5,
        reviewCount: 95,
        inStock: true,
        tags: ['baking', 'rich', 'organic'],
        sku: 'HO-CRM-HVY-001',
        availability: 'in_stock'
    },
    {
        id: 37,
        name: 'Sour Cream',
        price: 2.49,
        emoji: '🥣',
        category: 'dairy',
        brand: 'Daisy',
        description: 'Pure and natural sour cream, great for tacos and potatoes.',
        specifications: { 'Type': 'Original', 'Ingredients': 'Cultured Cream' },
        dimensions: { length: 10, width: 10, height: 8, unit: 'cm' },
        weight: { value: 454, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1624823183492-959885e3b018?w=400'],
        rating: 4.6,
        reviewCount: 140,
        inStock: true,
        tags: ['topping', 'creamy', 'cooking'],
        sku: 'DA-SCR-ORG-001',
        availability: 'in_stock'
    },
    {
        id: 38,
        name: 'Parmesan Cheese',
        price: 6.99,
        emoji: '🧀',
        category: 'dairy',
        brand: 'Belgioioso',
        description: 'Aged parmesan cheese wedge, perfect for grating over pasta.',
        specifications: { 'Type': 'Parmesan', 'Aged': '10 months' },
        dimensions: { length: 12, width: 8, height: 4, unit: 'cm' },
        weight: { value: 226, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1625085594861-86634a579220?w=400'],
        rating: 4.7,
        reviewCount: 115,
        inStock: true,
        tags: ['italian', 'cheese', 'aged'],
        sku: 'BG-CHE-PAR-001',
        availability: 'in_stock'
    },

    // Meat (IDs 11-12, 39-44)
    {
        id: 11,
        name: 'Boneless Chicken Breast',
        price: 7.99,
        emoji: '🍗',
        category: 'meat',
        brand: 'Premium Poultry',
        description: 'Tender boneless chicken breast, perfect for grilling.',
        specifications: { 'Cut': 'Boneless Breast', 'Grade': 'A' },
        dimensions: { length: 15, width: 10, height: 3, unit: 'cm' },
        weight: { value: 454, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=400'],
        rating: 4.4,
        reviewCount: 203,
        inStock: true,
        tags: ['tender', 'versatile', 'lean'],
        sku: 'PP-CHK-BRS-001',
        availability: 'in_stock'
    },
    {
        id: 12,
        name: 'Fresh Atlantic Salmon',
        price: 12.99,
        emoji: '🐟',
        category: 'meat',
        brand: 'Ocean Fresh Seafood',
        description: 'Premium Atlantic salmon fillet, rich in omega-3.',
        specifications: { 'Type': 'Atlantic Salmon', 'Omega-3': 'High' },
        dimensions: { length: 20, width: 8, height: 2, unit: 'cm' },
        weight: { value: 170, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400'],
        rating: 4.7,
        reviewCount: 178,
        inStock: true,
        tags: ['omega-3', 'premium', 'fresh'],
        sku: 'OFS-SAL-ATL-001',
        availability: 'in_stock'
    },
    {
        id: 39,
        name: 'Ground Beef 80/20',
        price: 5.99,
        emoji: '🥩',
        category: 'meat',
        brand: 'Ranchers Choice',
        description: 'Fresh ground beef, 80% lean, perfect for burgers.',
        specifications: { 'Lean': '80%', 'Fat': '20%' },
        dimensions: { length: 15, width: 15, height: 5, unit: 'cm' },
        weight: { value: 454, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1588168333986-5078d3ae3976?w=400'],
        rating: 4.5,
        reviewCount: 240,
        inStock: true,
        tags: ['burgers', 'beef', 'versatile'],
        sku: 'RC-BEF-GND-001',
        availability: 'in_stock'
    },
    {
        id: 40,
        name: 'Bacon Strips',
        price: 6.99,
        emoji: '🥓',
        category: 'meat',
        brand: 'Oscar Mayer',
        description: 'Thick cut hardwood smoked bacon.',
        specifications: { 'Cut': 'Thick', 'Smoked': 'Hardwood' },
        dimensions: { length: 25, width: 10, height: 2, unit: 'cm' },
        weight: { value: 340, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1606851094655-b2593a9af63f?w=400'],
        rating: 4.8,
        reviewCount: 310,
        inStock: true,
        tags: ['breakfast', 'smoked', 'savory'],
        sku: 'OM-BAC-THK-001',
        availability: 'in_stock'
    },
    {
        id: 41,
        name: 'Pork Chops',
        price: 6.49,
        emoji: '🥩',
        category: 'meat',
        brand: 'Prairie Fresh',
        description: 'Bone-in pork chops, juicy and flavorful.',
        specifications: { 'Cut': 'Bone-in', 'Origin': 'USA' },
        dimensions: { length: 15, width: 10, height: 4, unit: 'cm' },
        weight: { value: 454, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1544378730-8b5104b1378b?w=400'],
        rating: 4.4,
        reviewCount: 125,
        inStock: true,
        tags: ['dinner', 'pork', 'juicy'],
        sku: 'PF-PRK-CHP-001',
        availability: 'in_stock'
    },
    {
        id: 42,
        name: 'Turkey Breast Slices',
        price: 5.49,
        emoji: '🥪',
        category: 'meat',
        brand: 'Hillshire Farm',
        description: 'Oven roasted turkey breast slices for sandwiches.',
        specifications: { 'Type': 'Oven Roasted', 'Sliced': 'Yes' },
        dimensions: { length: 15, width: 15, height: 3, unit: 'cm' },
        weight: { value: 255, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1528750997573-59b8b6ee58cd?w=400'],
        rating: 4.5,
        reviewCount: 160,
        inStock: true,
        tags: ['lunch', 'sandwich', 'lean'],
        sku: 'HF-TUR-SLC-001',
        availability: 'in_stock'
    },
    {
        id: 43,
        name: 'Shrimp',
        price: 14.99,
        emoji: '🦐',
        category: 'meat',
        brand: 'Sea Best',
        description: 'Large raw shrimp, peeled and deveined.',
        specifications: { 'Size': 'Large', 'Prepared': 'Peeled' },
        dimensions: { length: 20, width: 20, height: 5, unit: 'cm' },
        weight: { value: 454, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=400'],
        rating: 4.6,
        reviewCount: 145,
        inStock: true,
        tags: ['seafood', 'quick', 'protein'],
        sku: 'SB-SHR-LRG-001',
        availability: 'in_stock'
    },
    {
        id: 44,
        name: 'Hot Dogs',
        price: 3.99,
        emoji: '🌭',
        category: 'meat',
        brand: 'Ball Park',
        description: 'Classic beef hot dogs, great for grilling.',
        specifications: { 'Meat': 'Beef', 'Count': '8' },
        dimensions: { length: 15, width: 10, height: 4, unit: 'cm' },
        weight: { value: 425, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1612392062631-94dd858cba88?w=400'],
        rating: 4.2,
        reviewCount: 190,
        inStock: true,
        tags: ['grilling', 'summer', 'quick'],
        sku: 'BP-DOG-BEF-001',
        availability: 'in_stock'
    },

    // Bakery (IDs 13, 45-50)
    {
        id: 13,
        name: 'Sourdough Bread',
        price: 4.49,
        emoji: '🍞',
        category: 'bakery',
        brand: 'Artisan Bakery',
        description: 'Freshly baked sourdough bread with a crispy crust.',
        specifications: { 'Type': 'Sourdough', 'Origin': 'Local' },
        dimensions: { length: 30, width: 10, height: 10, unit: 'cm' },
        weight: { value: 680, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400'],
        rating: 4.8,
        reviewCount: 245,
        inStock: true,
        tags: ['artisan', 'fresh', 'crispy'],
        sku: 'AB-BRD-SOU-001',
        availability: 'in_stock'
    },
    {
        id: 45,
        name: 'Whole Wheat Bread',
        price: 3.29,
        emoji: '🍞',
        category: 'bakery',
        brand: 'Nature\'s Own',
        description: 'Soft whole wheat sandwich bread, 100% whole grain.',
        specifications: { 'Type': 'Whole Wheat', 'Grain': '100%' },
        dimensions: { length: 30, width: 10, height: 10, unit: 'cm' },
        weight: { value: 567, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1598373182133-52452f7691ef?w=400'],
        rating: 4.4,
        reviewCount: 180,
        inStock: true,
        tags: ['healthy', 'sandwich', 'fiber'],
        sku: 'NO-BRD-WHT-001',
        availability: 'in_stock'
    },
    {
        id: 46,
        name: 'Bagels',
        price: 3.99,
        emoji: '🥯',
        category: 'bakery',
        brand: 'Thomas',
        description: 'Plain bagels, chewy and pre-sliced.',
        specifications: { 'Type': 'Plain', 'Count': '6' },
        dimensions: { length: 25, width: 10, height: 10, unit: 'cm' },
        weight: { value: 567, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1585478683096-481e0a57052e?w=400'],
        rating: 4.5,
        reviewCount: 210,
        inStock: true,
        tags: ['breakfast', 'chewy', 'toasted'],
        sku: 'TH-BAG-PLN-001',
        availability: 'in_stock'
    },
    {
        id: 47,
        name: 'Croissants',
        price: 5.99,
        emoji: '🥐',
        category: 'bakery',
        brand: 'La Boulangerie',
        description: 'Buttery flaky croissants, pack of 4.',
        specifications: { 'Type': 'Butter', 'Count': '4' },
        dimensions: { length: 20, width: 15, height: 8, unit: 'cm' },
        weight: { value: 240, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400'],
        rating: 4.7,
        reviewCount: 145,
        inStock: true,
        tags: ['buttery', 'breakfast', 'french'],
        sku: 'LB-CRO-BUT-001',
        availability: 'in_stock'
    },
    {
        id: 48,
        name: 'Hamburger Buns',
        price: 2.99,
        emoji: '🍔',
        category: 'bakery',
        brand: 'Ball Park',
        description: 'Soft white hamburger buns, pack of 8.',
        specifications: { 'Type': 'White', 'Count': '8' },
        dimensions: { length: 30, width: 15, height: 8, unit: 'cm' },
        weight: { value: 340, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400'],
        rating: 4.3,
        reviewCount: 165,
        inStock: true,
        tags: ['grilling', 'soft', 'summer'],
        sku: 'BP-BUN-HAM-001',
        availability: 'in_stock'
    },
    {
        id: 49,
        name: 'Tortillas',
        price: 2.49,
        emoji: '🌮',
        category: 'bakery',
        brand: 'Mission',
        description: 'Soft flour tortillas, taco size.',
        specifications: { 'Type': 'Flour', 'Size': 'Medium' },
        dimensions: { length: 20, width: 20, height: 2, unit: 'cm' },
        weight: { value: 496, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1564767667012-549689a96794?w=400'],
        rating: 4.6,
        reviewCount: 230,
        inStock: true,
        tags: ['mexican', 'tacos', 'soft'],
        sku: 'MI-TOR-FLO-001',
        availability: 'in_stock'
    },
    {
        id: 50,
        name: 'Chocolate Chip Cookies',
        price: 4.99,
        emoji: '🍪',
        category: 'bakery',
        brand: 'Bakery Fresh',
        description: 'Soft baked chocolate chip cookies, pack of 12.',
        specifications: { 'Type': 'Chocolate Chip', 'Count': '12' },
        dimensions: { length: 20, width: 15, height: 8, unit: 'cm' },
        weight: { value: 380, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1499636138143-bd649043ea52?w=400'],
        rating: 4.7,
        reviewCount: 280,
        inStock: true,
        tags: ['sweet', 'dessert', 'treat'],
        sku: 'BF-COO-CHC-001',
        availability: 'in_stock'
    },
    // Pantry & Condiments (IDs 14, 51-65)
    {
        id: 14,
        name: 'Extra Virgin Olive Oil',
        price: 8.99,
        emoji: '🫒',
        category: 'condiments',
        brand: 'Mediterranean Gold',
        description: 'Premium extra virgin olive oil from Greece.',
        specifications: { 'Type': 'Extra Virgin', 'Origin': 'Greece' },
        dimensions: { length: 8, width: 8, height: 20, unit: 'cm' },
        weight: { value: 500, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400'],
        rating: 4.6,
        reviewCount: 167,
        inStock: true,
        tags: ['premium', 'cooking', 'dressing'],
        sku: 'MG-OIL-EVO-001',
        availability: 'in_stock'
    },
    {
        id: 51,
        name: 'Honey Nut Cereal',
        price: 3.99,
        emoji: '🥣',
        category: 'grains',
        brand: 'Morning Crunch',
        description: 'Sweetened whole grain oat cereal with honey and almonds.',
        specifications: { 'Type': 'Oats', 'Flavor': 'Honey Nut' },
        dimensions: { length: 20, width: 8, height: 30, unit: 'cm' },
        weight: { value: 340, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1521483450569-e33809c08751?w=400'],
        rating: 4.5,
        reviewCount: 210,
        inStock: true,
        tags: ['breakfast', 'fiber', 'sweet'],
        sku: 'MC-CER-HON-001',
        availability: 'in_stock'
    },
    {
        id: 52,
        name: 'Rolled Oats',
        price: 2.99,
        emoji: '🥣',
        category: 'grains',
        brand: 'Quaker',
        description: 'Old fashioned rolled oats, 100% whole grain.',
        specifications: { 'Type': 'Old Fashioned', 'Grain': 'Whole' },
        dimensions: { length: 12, width: 12, height: 20, unit: 'cm' },
        weight: { value: 510, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1517093725432-a9391ff95d6d?w=400'],
        rating: 4.7,
        reviewCount: 180,
        inStock: true,
        tags: ['breakfast', 'healthy', 'fiber'],
        sku: 'QK-OAT-ROL-001',
        availability: 'in_stock'
    },
    {
        id: 53,
        name: 'Pasta Spaghetti',
        price: 1.49,
        emoji: '🍝',
        category: 'grains',
        brand: 'Barilla',
        description: 'Classic spaghetti pasta, made with durum wheat.',
        specifications: { 'Type': 'Spaghetti', 'Grain': 'Durum Wheat' },
        dimensions: { length: 30, width: 5, height: 2, unit: 'cm' },
        weight: { value: 454, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1598866594230-a7c12756260f?w=400'],
        rating: 4.6,
        reviewCount: 250,
        inStock: true,
        tags: ['dinner', 'italian', 'pantry'],
        sku: 'BA-PAS-SPA-001',
        availability: 'in_stock'
    },
    {
        id: 54,
        name: 'Tomato Sauce',
        price: 1.99,
        emoji: '🍅',
        category: 'condiments',
        brand: 'Prego',
        description: 'Traditional Italian tomato sauce with basil.',
        specifications: { 'Type': 'Traditional', 'Flavor': 'Basil' },
        dimensions: { length: 8, width: 8, height: 15, unit: 'cm' },
        weight: { value: 680, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1607301406259-dfb31435b571?w=400'],
        rating: 4.4,
        reviewCount: 190,
        inStock: true,
        tags: ['dinner', 'italian', 'sauce'],
        sku: 'PR-SAU-TOM-001',
        availability: 'in_stock'
    },
    {
        id: 55,
        name: 'Basmati Rice',
        price: 4.99,
        emoji: '🍚',
        category: 'grains',
        brand: 'Royal',
        description: 'Aromatic long grain basmati rice.',
        specifications: { 'Type': 'Basmati', 'Grain': 'Long' },
        dimensions: { length: 20, width: 15, height: 5, unit: 'cm' },
        weight: { value: 907, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400'],
        rating: 4.7,
        reviewCount: 160,
        inStock: true,
        tags: ['dinner', 'asian', 'pantry'],
        sku: 'RY-RIC-BAS-001',
        availability: 'in_stock'
    },
    {
        id: 56,
        name: 'Black Beans',
        price: 0.99,
        emoji: '🫘',
        category: 'canned',
        brand: 'Goya',
        description: 'Canned black beans, ready to eat.',
        specifications: { 'Type': 'Black', 'Preparation': 'Canned' },
        dimensions: { length: 8, width: 8, height: 10, unit: 'cm' },
        weight: { value: 425, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1563502310703-1e8d35676e64?w=400'],
        rating: 4.5,
        reviewCount: 120,
        inStock: true,
        tags: ['mexican', 'protein', 'pantry'],
        sku: 'GY-BEA-BLK-001',
        availability: 'in_stock'
    },
    {
        id: 57,
        name: 'Soy Sauce',
        price: 2.99,
        emoji: '🥢',
        category: 'condiments',
        brand: 'Kikkoman',
        description: 'Traditionally brewed soy sauce.',
        specifications: { 'Type': 'Brewed', 'Sodium': 'Regular' },
        dimensions: { length: 6, width: 6, height: 15, unit: 'cm' },
        weight: { value: 296, unit: 'ml' },
        imageUrls: ['https://images.unsplash.com/photo-1598511726623-d0996d53f5d5?w=400'],
        rating: 4.8,
        reviewCount: 220,
        inStock: true,
        tags: ['asian', 'cooking', 'condiment'],
        sku: 'KK-SOY-SAU-001',
        availability: 'in_stock'
    },
    {
        id: 58,
        name: 'Peanut Butter',
        price: 3.49,
        emoji: '🥜',
        category: 'condiments',
        brand: 'Jif',
        description: 'Creamy peanut butter, smooth and delicious.',
        specifications: { 'Type': 'Creamy', 'Nut': 'Peanut' },
        dimensions: { length: 8, width: 8, height: 12, unit: 'cm' },
        weight: { value: 454, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1528751012705-46a446429120?w=400'],
        rating: 4.7,
        reviewCount: 310,
        inStock: true,
        tags: ['sandwich', 'protein', 'snack'],
        sku: 'JF-PEA-BUT-001',
        availability: 'in_stock'
    },
    {
        id: 59,
        name: 'Strawberry Jelly',
        price: 2.99,
        emoji: '🍓',
        category: 'condiments',
        brand: 'Smuckers',
        description: 'Sweet strawberry jelly, perfect for PB&J.',
        specifications: { 'Flavor': 'Strawberry', 'Type': 'Jelly' },
        dimensions: { length: 8, width: 8, height: 12, unit: 'cm' },
        weight: { value: 510, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1589733955941-5eeaf752f6dd?w=400'],
        rating: 4.6,
        reviewCount: 180,
        inStock: true,
        tags: ['sandwich', 'sweet', 'breakfast'],
        sku: 'SM-JEL-STR-001',
        availability: 'in_stock'
    },
    {
        id: 60,
        name: 'All-Purpose Flour',
        price: 3.99,
        emoji: '🥡',
        category: 'baking',
        brand: 'Gold Medal',
        description: 'Enriched bleached all-purpose flour.',
        specifications: { 'Type': 'All-Purpose', 'Bleached': 'Yes' },
        dimensions: { length: 15, width: 10, height: 20, unit: 'cm' },
        weight: { value: 2268, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1627485937980-221c88ac04f9?w=400'],
        rating: 4.5,
        reviewCount: 150,
        inStock: true,
        tags: ['baking', 'pantry', 'staple'],
        sku: 'GM-FLO-ALL-001',
        availability: 'in_stock'
    },
    {
        id: 61,
        name: 'Granulated Sugar',
        price: 2.99,
        emoji: '🧂',
        category: 'baking',
        brand: 'Domino',
        description: 'Pure cane granulated sugar.',
        specifications: { 'Type': 'Granulated', 'Source': 'Cane' },
        dimensions: { length: 15, width: 10, height: 20, unit: 'cm' },
        weight: { value: 1814, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400'],
        rating: 4.7,
        reviewCount: 190,
        inStock: true,
        tags: ['baking', 'sweet', 'pantry'],
        sku: 'DM-SUG-GRA-001',
        availability: 'in_stock'
    },
    {
        id: 62,
        name: 'Canned Soup',
        price: 1.99,
        emoji: '🥣',
        category: 'canned',
        brand: 'Campbells',
        description: 'Chicken noodle soup, classic comfort food.',
        specifications: { 'Flavor': 'Chicken Noodle', 'Type': 'Condensed' },
        dimensions: { length: 8, width: 8, height: 10, unit: 'cm' },
        weight: { value: 305, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1547592166-23acbe3b624b?w=400'],
        rating: 4.4,
        reviewCount: 210,
        inStock: true,
        tags: ['lunch', 'quick', 'comfort'],
        sku: 'CP-SOU-CHK-001',
        availability: 'in_stock'
    },
    {
        id: 63,
        name: 'Ramen Noodles',
        price: 0.49,
        emoji: '🍜',
        category: 'grains',
        brand: 'Maruchan',
        description: 'Instant ramen noodles, chicken flavor.',
        specifications: { 'Flavor': 'Chicken', 'Type': 'Instant' },
        dimensions: { length: 10, width: 10, height: 3, unit: 'cm' },
        weight: { value: 85, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400'],
        rating: 4.2,
        reviewCount: 350,
        inStock: true,
        tags: ['quick', 'budget', 'asian'],
        sku: 'MR-RAM-CHK-001',
        availability: 'in_stock'
    },
    {
        id: 64,
        name: 'Potato Chips',
        price: 3.99,
        emoji: '🥔',
        category: 'snacks',
        brand: 'Lays',
        description: 'Classic salted potato chips, crispy and delicious.',
        specifications: { 'Flavor': 'Classic', 'Type': 'Fried' },
        dimensions: { length: 20, width: 15, height: 30, unit: 'cm' },
        weight: { value: 226, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1566478919030-41567d132d13?w=400'],
        rating: 4.5,
        reviewCount: 280,
        inStock: true,
        tags: ['snack', 'party', 'salty'],
        sku: 'LY-CHP-CLA-001',
        availability: 'in_stock'
    },
    {
        id: 65,
        name: 'Salsa',
        price: 3.49,
        emoji: '🍅',
        category: 'condiments',
        brand: 'Tostitos',
        description: 'Medium chunky salsa, perfect for dipping.',
        specifications: { 'Heat': 'Medium', 'Texture': 'Chunky' },
        dimensions: { length: 8, width: 8, height: 12, unit: 'cm' },
        weight: { value: 440, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1599321955726-e04842d961e6?w=400'],
        rating: 4.6,
        reviewCount: 190,
        inStock: true,
        tags: ['party', 'dip', 'mexican'],
        sku: 'TS-SAL-MED-001',
        availability: 'in_stock'
    },

    // Beverages (IDs 15, 66-70)
    {
        id: 15,
        name: 'Premium Coffee Beans',
        price: 11.99,
        emoji: '☕',
        category: 'beverages',
        brand: 'Mountain Roast',
        description: 'Freshly roasted Arabica coffee beans.',
        specifications: { 'Type': 'Arabica', 'Roast': 'Medium' },
        dimensions: { length: 12, width: 8, height: 6, unit: 'cm' },
        weight: { value: 340, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400'],
        rating: 4.7,
        reviewCount: 289,
        inStock: true,
        tags: ['arabica', 'fresh', 'bold'],
        sku: 'MR-COF-BEA-001',
        availability: 'in_stock'
    },
    {
        id: 66,
        name: 'Orange Juice',
        price: 4.99,
        emoji: '🍊',
        category: 'beverages',
        brand: 'Tropicana',
        description: '100% pure orange juice, no pulp.',
        specifications: { 'Pulp': 'No', 'Type': '100% Juice' },
        dimensions: { length: 10, width: 10, height: 25, unit: 'cm' },
        weight: { value: 1500, unit: 'ml' },
        imageUrls: ['https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=400'],
        rating: 4.6,
        reviewCount: 220,
        inStock: true,
        tags: ['breakfast', 'vitamin-c', 'fresh'],
        sku: 'TR-JUI-ORA-001',
        availability: 'in_stock'
    },
    {
        id: 67,
        name: 'Cola Soda',
        price: 1.99,
        emoji: '🥤',
        category: 'beverages',
        brand: 'Coca-Cola',
        description: 'Classic cola soda, 2 liter bottle.',
        specifications: { 'Type': 'Cola', 'Size': '2L' },
        dimensions: { length: 10, width: 10, height: 30, unit: 'cm' },
        weight: { value: 2000, unit: 'ml' },
        imageUrls: ['https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400'],
        rating: 4.5,
        reviewCount: 310,
        inStock: true,
        tags: ['party', 'drink', 'sweet'],
        sku: 'CC-SOD-COL-001',
        availability: 'in_stock'
    },
    {
        id: 68,
        name: 'Almond Milk',
        price: 3.49,
        emoji: '🥛',
        category: 'beverages',
        brand: 'Almond Breeze',
        description: 'Unsweetened vanilla almond milk.',
        specifications: { 'Type': 'Almond', 'Flavor': 'Vanilla' },
        dimensions: { length: 10, width: 8, height: 20, unit: 'cm' },
        weight: { value: 946, unit: 'ml' },
        imageUrls: ['https://images.unsplash.com/photo-1600788886242-5c96aabe3757?w=400'],
        rating: 4.7,
        reviewCount: 180,
        inStock: true,
        tags: ['dairy-free', 'healthy', 'vegan'],
        sku: 'AB-MIL-ALM-001',
        availability: 'in_stock'
    },
    {
        id: 69,
        name: 'Craft Beer',
        price: 10.99,
        emoji: '🍺',
        category: 'alcohol',
        brand: 'Local Brew',
        description: 'IPA craft beer, 6 pack.',
        specifications: { 'Type': 'IPA', 'ABV': '6.5%' },
        dimensions: { length: 20, width: 15, height: 20, unit: 'cm' },
        weight: { value: 2000, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1608270586620-248524c67de9?w=400'],
        rating: 4.6,
        reviewCount: 140,
        inStock: true,
        tags: ['party', 'alcohol', 'adult'],
        sku: 'LB-BER-IPA-001',
        availability: 'in_stock'
    },
    {
        id: 70,
        name: 'Red Wine',
        price: 14.99,
        emoji: '🍷',
        category: 'alcohol',
        brand: 'Vineyard Select',
        description: 'Cabernet Sauvignon, rich and full-bodied.',
        specifications: { 'Type': 'Cabernet', 'Origin': 'Napa' },
        dimensions: { length: 8, width: 8, height: 30, unit: 'cm' },
        weight: { value: 750, unit: 'ml' },
        imageUrls: ['https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400'],
        rating: 4.8,
        reviewCount: 160,
        inStock: true,
        tags: ['dinner', 'alcohol', 'premium'],
        sku: 'VS-WIN-RED-001',
        availability: 'in_stock'
    },

    // Frozen (IDs 17, 71-73)
    {
        id: 17,
        name: 'Frozen Mixed Vegetables',
        price: 2.99,
        emoji: '🥦',
        category: 'frozen',
        brand: 'Green Harvest',
        description: 'Frozen mixed vegetables including broccoli, carrots, and peas.',
        specifications: { 'Contents': 'Broccoli, carrots, peas', 'Frozen': 'Yes' },
        dimensions: { length: 15, width: 10, height: 5, unit: 'cm' },
        weight: { value: 400, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400'],
        rating: 4.2,
        reviewCount: 145,
        inStock: true,
        tags: ['frozen', 'mixed', 'quick'],
        sku: 'GH-VEG-MIX-001',
        availability: 'in_stock'
    },
    {
        id: 71,
        name: 'Frozen Pizza',
        price: 6.99,
        emoji: '🍕',
        category: 'frozen',
        brand: 'DiGiorno',
        description: 'Rising crust pepperoni pizza.',
        specifications: { 'Topping': 'Pepperoni', 'Crust': 'Rising' },
        dimensions: { length: 30, width: 30, height: 3, unit: 'cm' },
        weight: { value: 800, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400'],
        rating: 4.4,
        reviewCount: 250,
        inStock: true,
        tags: ['dinner', 'quick', 'comfort'],
        sku: 'DG-PIZ-PEP-001',
        availability: 'in_stock'
    },
    {
        id: 72,
        name: 'Vanilla Ice Cream',
        price: 4.99,
        emoji: '🍦',
        category: 'frozen',
        brand: 'Breyers',
        description: 'Natural vanilla bean ice cream.',
        specifications: { 'Flavor': 'Vanilla', 'Type': 'Ice Cream' },
        dimensions: { length: 15, width: 10, height: 10, unit: 'cm' },
        weight: { value: 1400, unit: 'ml' },
        imageUrls: ['https://images.unsplash.com/photo-1560008581-09826d1de69e?w=400'],
        rating: 4.6,
        reviewCount: 280,
        inStock: true,
        tags: ['dessert', 'sweet', 'frozen'],
        sku: 'BR-ICE-VAN-001',
        availability: 'in_stock'
    },
    {
        id: 73,
        name: 'Frozen Waffles',
        price: 3.49,
        emoji: '🧇',
        category: 'frozen',
        brand: 'Eggo',
        description: 'Homestyle frozen waffles, pack of 10.',
        specifications: { 'Type': 'Homestyle', 'Count': '10' },
        dimensions: { length: 10, width: 10, height: 20, unit: 'cm' },
        weight: { value: 350, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=400'],
        rating: 4.3,
        reviewCount: 190,
        inStock: true,
        tags: ['breakfast', 'quick', 'frozen'],
        sku: 'EG-WAF-HOM-001',
        availability: 'in_stock'
    },

    // Household & Baby & Pet (IDs 18-20, 74-80)
    {
        id: 18,
        name: 'Whey Protein Powder',
        price: 29.99,
        emoji: '💪',
        category: 'health',
        brand: 'FitLife Nutrition',
        description: 'High-quality whey protein powder, vanilla flavor.',
        specifications: { 'Type': 'Whey', 'Flavor': 'Vanilla' },
        dimensions: { length: 12, width: 12, height: 20, unit: 'cm' },
        weight: { value: 907, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400'],
        rating: 4.6,
        reviewCount: 312,
        inStock: true,
        tags: ['protein', 'fitness', 'health'],
        sku: 'FLN-PRO-WHEY-001',
        availability: 'in_stock'
    },
    {
        id: 19,
        name: 'Laundry Detergent',
        price: 9.99,
        emoji: '🧺',
        category: 'household',
        brand: 'Clean & Fresh',
        description: 'Powerful liquid laundry detergent.',
        specifications: { 'Type': 'Liquid', 'Scent': 'Fresh' },
        dimensions: { length: 10, width: 8, height: 25, unit: 'cm' },
        weight: { value: 2000, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?w=400'],
        rating: 4.3,
        reviewCount: 178,
        inStock: true,
        tags: ['cleaning', 'laundry', 'household'],
        sku: 'CF-DET-LAU-001',
        availability: 'in_stock'
    },
    {
        id: 20,
        name: 'Premium Dog Food',
        price: 34.99,
        emoji: '🐕',
        category: 'pet',
        brand: 'Pet Nutrition Plus',
        description: 'Complete and balanced dry dog food.',
        specifications: { 'Type': 'Dry', 'Life Stage': 'Adult' },
        dimensions: { length: 20, width: 15, height: 10, unit: 'cm' },
        weight: { value: 5443, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=400'],
        rating: 4.5,
        reviewCount: 267,
        inStock: true,
        tags: ['pet', 'dog', 'premium'],
        sku: 'PNP-DOG-FOOD-001',
        availability: 'in_stock'
    },
    {
        id: 74,
        name: 'Paper Towels',
        price: 8.99,
        emoji: '🧻',
        category: 'household',
        brand: 'Bounty',
        description: 'Absorbent paper towels, 6 rolls.',
        specifications: { 'Count': '6', 'Ply': '2' },
        dimensions: { length: 30, width: 20, height: 40, unit: 'cm' },
        weight: { value: 1000, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=400'],
        rating: 4.7,
        reviewCount: 320,
        inStock: true,
        tags: ['cleaning', 'kitchen', 'household'],
        sku: 'BO-PAP-TOW-001',
        availability: 'in_stock'
    },
    {
        id: 75,
        name: 'Toilet Paper',
        price: 12.99,
        emoji: '🧻',
        category: 'household',
        brand: 'Charmin',
        description: 'Ultra soft toilet paper, 12 mega rolls.',
        specifications: { 'Count': '12', 'Softness': 'Ultra' },
        dimensions: { length: 40, width: 30, height: 20, unit: 'cm' },
        weight: { value: 1500, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1584556812952-905ffd0c611f?w=400'],
        rating: 4.8,
        reviewCount: 410,
        inStock: true,
        tags: ['bathroom', 'household', 'soft'],
        sku: 'CH-TOI-PAP-001',
        availability: 'in_stock'
    },
    {
        id: 76,
        name: 'Dish Soap',
        price: 2.99,
        emoji: '🧼',
        category: 'household',
        brand: 'Dawn',
        description: 'Grease fighting dish soap, original scent.',
        specifications: { 'Type': 'Liquid', 'Scent': 'Original' },
        dimensions: { length: 8, width: 5, height: 20, unit: 'cm' },
        weight: { value: 500, unit: 'ml' },
        imageUrls: ['https://images.unsplash.com/photo-1585832770485-e68a5dbfad52?w=400'],
        rating: 4.8,
        reviewCount: 350,
        inStock: true,
        tags: ['cleaning', 'kitchen', 'dish'],
        sku: 'DA-DIS-SOA-001',
        availability: 'in_stock'
    },
    {
        id: 77,
        name: 'Baby Diapers',
        price: 24.99,
        emoji: '👶',
        category: 'baby',
        brand: 'Pampers',
        description: 'Soft and absorbent diapers, size 3.',
        specifications: { 'Size': '3', 'Count': '80' },
        dimensions: { length: 40, width: 20, height: 20, unit: 'cm' },
        weight: { value: 2000, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1519689680058-324335c77eba?w=400'],
        rating: 4.7,
        reviewCount: 290,
        inStock: true,
        tags: ['baby', 'diapers', 'care'],
        sku: 'PA-DIA-SZ3-001',
        availability: 'in_stock'
    },
    {
        id: 78,
        name: 'Baby Wipes',
        price: 3.99,
        emoji: '👶',
        category: 'baby',
        brand: 'Huggies',
        description: 'Sensitive skin baby wipes, fragrance free.',
        specifications: { 'Type': 'Sensitive', 'Count': '64' },
        dimensions: { length: 20, width: 10, height: 5, unit: 'cm' },
        weight: { value: 400, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1556228720-1987d7d8c069?w=400'],
        rating: 4.6,
        reviewCount: 210,
        inStock: true,
        tags: ['baby', 'wipes', 'care'],
        sku: 'HU-WIP-SEN-001',
        availability: 'in_stock'
    },
    {
        id: 79,
        name: 'Cat Food',
        price: 14.99,
        emoji: '🐈',
        category: 'pet',
        brand: 'Meow Mix',
        description: 'Dry cat food, seafood medley flavor.',
        specifications: { 'Flavor': 'Seafood', 'Type': 'Dry' },
        dimensions: { length: 15, width: 10, height: 25, unit: 'cm' },
        weight: { value: 1500, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1589924691195-41432c84c161?w=400'],
        rating: 4.4,
        reviewCount: 180,
        inStock: true,
        tags: ['pet', 'cat', 'food'],
        sku: 'MM-CAT-FOO-001',
        availability: 'in_stock'
    },
    {
        id: 80,
        name: 'Cat Litter',
        price: 12.99,
        emoji: '🐈‍⬛',
        category: 'pet',
        brand: 'Tidy Cats',
        description: 'Clumping cat litter, odor control.',
        specifications: { 'Type': 'Clumping', 'Scent': 'Fresh' },
        dimensions: { length: 30, width: 20, height: 10, unit: 'cm' },
        weight: { value: 5000, unit: 'g' },
        imageUrls: ['https://images.unsplash.com/photo-1623366302587-b38b1ddaefd9?w=400'],
        rating: 4.5,
        reviewCount: 160,
        inStock: true,
        tags: ['pet', 'cat', 'litter'],
        sku: 'TC-CAT-LIT-001',
        availability: 'in_stock'
    }
];

// Customer segment definitions with realistic behaviors
export const CUSTOMER_SEGMENTS: CustomerSegment[] = [
    {
        type: 'budget',
        basketSize: { min: 3, max: 8 },
        preferredCategories: ['grains', 'canned', 'frozen', 'household'],
        frequencyWeight: 0.25
    },
    {
        type: 'regular',
        basketSize: { min: 5, max: 12 },
        preferredCategories: ['dairy', 'meat', 'vegetables', 'fruits', 'bakery', 'beverages'],
        frequencyWeight: 0.35
    },
    {
        type: 'premium',
        basketSize: { min: 8, max: 18 },
        preferredCategories: ['meat', 'dairy', 'fruits', 'vegetables', 'health', 'alcohol', 'sweets'],
        frequencyWeight: 0.15
    },
    {
        type: 'health_conscious',
        basketSize: { min: 6, max: 14 },
        preferredCategories: ['health', 'fruits', 'vegetables', 'dairy', 'meat', 'grains'],
        frequencyWeight: 0.12
    },
    {
        type: 'convenience',
        basketSize: { min: 2, max: 6 },
        preferredCategories: ['frozen', 'snacks', 'beverages', 'bakery'],
        frequencyWeight: 0.08
    },
    {
        type: 'family',
        basketSize: { min: 12, max: 25 },
        preferredCategories: ['dairy', 'meat', 'vegetables', 'fruits', 'snacks', 'household', 'bakery', 'frozen', 'baby', 'pet'],
        frequencyWeight: 0.05
    }
];

// Shopping patterns based on common real-world associations
// IMPORTANT: These names MUST match PRODUCT_CATALOG names exactly
export const SHOPPING_PATTERNS = {
    breakfast: [
        ['Whole Milk', 'Honey Nut Cereal', 'Fresh Bananas', 'Orange Juice'],
        ['Sourdough Bread', 'Large Eggs', 'Bacon Strips', 'Unsalted Butter', 'Premium Coffee Beans'],
        ['Greek Yogurt', 'Fresh Blueberries', 'Honey Nut Cereal'],
        ['Bagels', 'Cream Cheese', 'Premium Coffee Beans', 'Orange Juice'],
        ['Rolled Oats', 'Whole Milk', 'Fresh Strawberries'],
        ['Croissants', 'Unsalted Butter', 'Premium Coffee Beans', 'Orange Juice']
    ],

    dinner_italian: [
        ['Pasta Spaghetti', 'Tomato Sauce', 'Parmesan Cheese', 'Extra Virgin Olive Oil', 'Sourdough Bread'],
        ['Pasta Spaghetti', 'Ground Beef 80/20', 'Tomato Sauce', 'Yellow Onions'],
        ['Frozen Pizza', 'Cola Soda', 'Potato Chips']
    ],

    dinner_american: [
        ['Ground Beef 80/20', 'Hamburger Buns', 'Cheddar Cheese Block', 'Organic Romaine Lettuce', 'Vine-Ripened Tomatoes', 'Potato Chips'],
        ['Boneless Chicken Breast', 'Basmati Rice', 'Fresh Broccoli Crowns', 'Soy Sauce'],
        ['Pork Chops', 'Russet Potatoes', 'Frozen Mixed Vegetables', 'Unsalted Butter'],
        ['Fresh Atlantic Salmon', 'Fresh Spinach', 'Extra Virgin Olive Oil']
    ],

    dinner_mexican: [
        ['Tortillas', 'Ground Beef 80/20', 'Cheddar Cheese Block', 'Organic Romaine Lettuce', 'Vine-Ripened Tomatoes', 'Sour Cream', 'Salsa'],
        ['Boneless Chicken Breast', 'Basmati Rice', 'Black Beans', 'Tortillas', 'Avocado']
    ],

    dinner_asian: [
        ['Basmati Rice', 'Soy Sauce', 'Boneless Chicken Breast', 'Fresh Broccoli Crowns', 'Baby Carrots'],
        ['Ramen Noodles', 'Frozen Mixed Vegetables', 'Soy Sauce', 'Large Eggs'],
        ['Shrimp', 'Basmati Rice', 'Red Bell Peppers', 'Soy Sauce']
    ],

    salad: [
        ['Organic Romaine Lettuce', 'Vine-Ripened Tomatoes', 'Cucumber', 'Extra Virgin Olive Oil'],
        ['Fresh Spinach', 'Fresh Strawberries', 'Extra Virgin Olive Oil'],
        ['Organic Romaine Lettuce', 'Boneless Chicken Breast', 'Parmesan Cheese']
    ],

    sandwich: [
        ['Whole Wheat Bread', 'Turkey Breast Slices', 'Cheddar Cheese Block', 'Organic Romaine Lettuce', 'Vine-Ripened Tomatoes'],
        ['Bagels', 'Cream Cheese', 'Fresh Atlantic Salmon', 'Cucumber'],
        ['Whole Wheat Bread', 'Peanut Butter', 'Strawberry Jelly', 'Fresh Bananas']
    ],

    baking: [
        ['All-Purpose Flour', 'Granulated Sugar', 'Unsalted Butter', 'Large Eggs', 'Chocolate Chip Cookies'],
        ['All-Purpose Flour', 'Chocolate Chip Cookies', 'Unsalted Butter', 'Granulated Sugar', 'Large Eggs']
    ],

    party: [
        ['Potato Chips', 'Salsa', 'Avocado', 'Cola Soda', 'Craft Beer'],
        ['Frozen Pizza', 'Craft Beer', 'Cola Soda'],
        ['Cheddar Cheese Block', 'Sourdough Bread', 'Red Wine', 'Red Seedless Grapes'],
        ['Potato Chips', 'Cola Soda', 'Chocolate Chip Cookies']
    ],

    snacking: [
        ['Potato Chips', 'Cola Soda'],
        ['Chocolate Chip Cookies', 'Whole Milk'],
        ['Dark Chocolate Bar', 'Vanilla Ice Cream'],
        ['Sourdough Bread', 'Cheddar Cheese Block'],
        ['Potato Chips', 'Cola Soda']
    ],

    healthy: [
        ['Greek Yogurt', 'Fresh Blueberries', 'Honey Nut Cereal'],
        ['Whey Protein Powder', 'Almond Milk', 'Fresh Bananas'],
        ['Boneless Chicken Breast', 'Basmati Rice', 'Fresh Broccoli Crowns', 'Extra Virgin Olive Oil'],
        ['Fresh Atlantic Salmon', 'Russet Potatoes', 'Fresh Spinach']
    ],

    quick_meal: [
        ['Frozen Pizza', 'Cola Soda'],
        ['Frozen Waffles', 'Orange Juice'],
        ['Canned Soup', 'Sourdough Bread', 'Cheddar Cheese Block'],
        ['Ramen Noodles', 'Large Eggs']
    ],

    household_shopping: [
        ['Laundry Detergent', 'Dish Soap', 'Paper Towels', 'Toilet Paper'],
        ['Paper Towels', 'Dish Soap', 'Sponge'],
        ['Laundry Detergent', 'Bleach']
    ],

    baby_care: [
        ['Baby Diapers', 'Baby Wipes', 'Baby Food'],
        ['Baby Lotion', 'Baby Shampoo', 'Baby Diapers']
    ],

    pet_care: [
        ['Premium Dog Food', 'Pet Treats'],
        ['Cat Litter', 'Cat Food', 'Pet Treats']
    ],

    impulse: [
        ['Dark Chocolate Bar'],
        ['Cola Soda'],
        ['Potato Chips'],
        ['Chocolate Chip Cookies'],
        ['Vanilla Ice Cream']
    ]
};

// Seasonal patterns
export const SEASONAL_ITEMS = {
    spring: ['Fresh Strawberries', 'Fresh Spinach', 'Organic Romaine Lettuce'],
    summer: ['Watermelon', 'Vanilla Ice Cream', 'Hot Dogs', 'Vine-Ripened Tomatoes'],
    fall: ['Honeycrisp Apples', 'Canned Soup'],
    winter: ['Canned Soup', 'Navel Oranges', 'Hot Chocolate']
};

// Time-based shopping patterns
export const TIME_PATTERNS = {
    morning: { weight: 0.3, patterns: ['breakfast', 'snacking', 'impulse'] },
    afternoon: { weight: 0.2, patterns: ['quick_meal', 'snacking', 'household_shopping'] },
    evening: { weight: 0.4, patterns: ['dinner_italian', 'dinner_american', 'dinner_mexican', 'dinner_asian', 'salad'] },
    night: { weight: 0.1, patterns: ['snacking', 'impulse', 'quick_meal'] }
};
