import { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Separator } from "@/components/ui/separator";
import { Progress } from "@/components/ui/progress";
import {
  ShoppingCart,
  TrendingUp,
  Sparkles,
  ArrowLeft,
  Plus,
  Minus,
  Star,
  Package,
  Truck,
  Shield,
  RotateCcw,
  Heart
} from "lucide-react";
import { toast } from "sonner";
import { runAprioriAlgorithm, sampleTransactions } from "@/lib/apriori";
import { PRODUCT_CATALOG } from "@/lib/data";
import { NotFoundErrorState, EmptyCartState } from "@/components/ErrorState";
import Footer from "@/components/Footer";
import type {
  Product,
  CartItem,
  WishlistItem,
  AprioriRule,
  Recommendation
} from "@/types";

const products: Product[] = PRODUCT_CATALOG;

const ProductDetail = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [cart, setCart] = useState<CartItem[]>([]);
  const [wishlist, setWishlist] = useState<WishlistItem[]>([]);
  const [rules, setRules] = useState<AprioriRule[]>([]);
  const [recommendations, setRecommendations] = useState<Recommendation[]>([]);
  const [quantity, setQuantity] = useState(1);

  const productId = parseInt(id || "0");
  const product = products.find(p => p.id === productId);

  useEffect(() => {
    // Load cart from localStorage
    const savedCart = localStorage.getItem('smartmart-cart');
    if (savedCart) {
      try {
        setCart(JSON.parse(savedCart));
      } catch (error) {
        console.error('Error loading cart from localStorage:', error);
      }
    }

    // Load wishlist from localStorage
    const savedWishlist = localStorage.getItem('smartmart-wishlist');
    if (savedWishlist) {
      try {
        setWishlist(JSON.parse(savedWishlist));
      } catch (error) {
        console.error('Error loading wishlist from localStorage:', error);
      }
    }

    // Track recently viewed product
    if (product) {
      const recentlyViewedKey = 'smartmart-recently-viewed';
      const maxRecentlyViewed = 10;

      try {
        const viewedData = localStorage.getItem(recentlyViewedKey);
        let recentlyViewed: Array<{ id: number; name: string; viewedAt: string }> = [];

        if (viewedData) {
          recentlyViewed = JSON.parse(viewedData);
        }

        // Remove if already exists (to avoid duplicates)
        recentlyViewed = recentlyViewed.filter(item => item.id !== product.id);

        // Add current product to the beginning
        recentlyViewed.unshift({
          id: product.id,
          name: product.name,
          viewedAt: new Date().toISOString()
        });

        // Keep only the last 10 items
        if (recentlyViewed.length > maxRecentlyViewed) {
          recentlyViewed = recentlyViewed.slice(0, maxRecentlyViewed);
        }

        localStorage.setItem(recentlyViewedKey, JSON.stringify(recentlyViewed));
      } catch (error) {
        console.error('Error tracking recently viewed product:', error);
      }
    }

    // Check if rules are cached with current parameters
    const cacheVersion = 'v2'; // Increment when parameters change
    const cachedRules = localStorage.getItem('smartmart-apriori-rules');
    const cachedVersion = localStorage.getItem('smartmart-cache-version');

    if (cachedRules && cachedVersion === cacheVersion) {
      try {
        setRules(JSON.parse(cachedRules));
      } catch (error) {
        console.error('Error loading cached rules:', error);
        // Fall back to computing
        computeRules();
      }
    } else {
      computeRules();
    }

    function computeRules() {
      // Compute Apriori association rules with optimized parameters
      const { associationRules: rawRules } = runAprioriAlgorithm(sampleTransactions(), 0.01, 0.20);
      // Keep all rules generated by the algorithm
      const associationRules = rawRules;

      console.log('📊 Raw rules generated:', rawRules.length);
      console.log('🎯 Filtered rules (lift > 1.0):', associationRules.length);
      if (associationRules.length > 0) {
        console.log('Sample rules:', associationRules.slice(0, 3).map(r => `${r.antecedent.join(' + ')} => ${r.consequent.join(' + ')} (conf: ${(r.confidence * 100).toFixed(1)}%)`));
      }
      setRules(associationRules);
      // Cache the results
      localStorage.setItem('smartmart-apriori-rules', JSON.stringify(associationRules));
      localStorage.setItem('smartmart-cache-version', 'v2');
    }
  }, [product]);

  useEffect(() => {
    // Save cart to localStorage whenever it changes
    localStorage.setItem('smartmart-cart', JSON.stringify(cart));
  }, [cart]);

  useEffect(() => {
    // Save wishlist to localStorage whenever it changes
    localStorage.setItem('smartmart-wishlist', JSON.stringify(wishlist));
  }, [wishlist]);

  useEffect(() => {
    // Generate enhanced recommendations based on cart and current product
    if (rules.length === 0) return;

    const cartItemSet = new Set(cart.map((item) => item.name));
    // Include current product in consideration for recommendations
    if (product) {
      cartItemSet.add(product.name);
    }

    const recommendedMap = new Map<string, {
      reasons: string[];
      confidence: number;
      support: number;
      lift: number;
      kulczynski: number;
      score: number;
      ruleCount: number;
    }>();

    rules.forEach((rule) => {
      const hasAllAntecedents = rule.antecedent.every((item) =>
        cartItemSet.has(item)
      );

      // Enhanced filtering: higher thresholds for better quality recommendations
      const hasGoodConfidence = rule.confidence > 0.3; // Increased from 0.2
      const hasGoodLift = (rule.lift || 1) > 1.2; // Only rules with meaningful lift
      const hasGoodSupport = rule.support > 0.01; // Minimum support threshold

      if (hasAllAntecedents && hasGoodConfidence && hasGoodLift && hasGoodSupport) {
        rule.consequent.forEach((consequentItem) => {
          // Don't recommend items already in cart or current product
          if (!cartItemSet.has(consequentItem) && consequentItem !== product?.name) {
            const existing = recommendedMap.get(consequentItem);
            const ruleScore = (rule.confidence * (rule.lift || 1) * (rule.kulczynski || 1)) / 3;

            if (!existing) {
              recommendedMap.set(consequentItem, {
                reasons: [`${rule.antecedent.join(' + ')} → ${consequentItem}`],
                confidence: rule.confidence,
                support: rule.support,
                lift: rule.lift || 1,
                kulczynski: rule.kulczynski || 1,
                score: ruleScore,
                ruleCount: 1,
              });
            } else {
              const newReason = `${rule.antecedent.join(' + ')} → ${consequentItem}`;
              if (!existing.reasons.includes(newReason)) {
                existing.reasons.push(newReason);
              }

              // Update with better metrics if this rule is stronger
              if (ruleScore > existing.score) {
                existing.confidence = rule.confidence;
                existing.support = rule.support;
                existing.lift = rule.lift || 1;
                existing.kulczynski = rule.kulczynski || 1;
                existing.score = ruleScore;
              }
              existing.ruleCount += 1;
            }
          }
        });
      }
    });

    console.log('🎯 Applied enhanced rules:', recommendedMap.size > 0 ? 'Some rules applied' : 'No rules applied');
    console.log('💡 Enhanced recommendations generated:', recommendedMap.size);
    if (recommendedMap.size > 0) {
      console.log('Recommended items:', Array.from(recommendedMap.keys()));
    }

    const recommendationsList = Array.from(recommendedMap.entries())
      .map(([productName, data]) => ({
        product: productName,
        reason: data.reasons,
        confidence: data.confidence,
        support: data.support,
        score: data.score,
        ruleCount: data.ruleCount,
        lift: data.lift,
      }))
      .sort((a, b) => {
        // Enhanced ranking: prioritize score, then confidence, then support
        if (Math.abs(b.score - a.score) > 0.01) return b.score - a.score;
        if (b.confidence !== a.confidence) return b.confidence - a.confidence;
        return b.support - a.support;
      })
      .slice(0, 6); // Limit to 6 recommendations

    // Enhanced fallback: use category-based recommendations when no rules apply
    if (recommendationsList.length === 0 && rules.length > 0) {
      console.log('⚠️ No recommendations found, using enhanced fallback');

      // Get items from same category as current product
      const currentCategory = product?.category;
      const categoryItems = products.filter(p =>
        p.category === currentCategory && p.id !== product?.id && !cartItemSet.has(p.name)
      );

      if (categoryItems.length > 0) {
        const categoryRecommendations = categoryItems
          .slice(0, 6)
          .map(catProduct => ({
            product: catProduct.name,
            reason: [`Similar category: ${currentCategory}`],
            confidence: 0.4, // Moderate confidence for category-based
            support: 0.05, // Default support
            score: 0.3, // Lower score than rule-based
            ruleCount: 1,
            lift: 1.0,
          }));

        console.log('🏷️ Category-based recommendations:', categoryRecommendations.length);
        setRecommendations(categoryRecommendations);
      } else {
        // Final fallback to most frequent items
        const itemFrequency = new Map<string, number>();
        rules.forEach(rule => {
          rule.antecedent.forEach(item => {
            itemFrequency.set(item, (itemFrequency.get(item) || 0) + rule.support);
          });
          rule.consequent.forEach(item => {
            itemFrequency.set(item, (itemFrequency.get(item) || 0) + rule.support);
          });
        });

        const fallbackRecommendations = Array.from(itemFrequency.entries())
          .filter(([item]) => !cartItemSet.has(item) && item !== product?.name)
          .sort((a, b) => b[1] - a[1])
          .slice(0, 6)
          .map(([productName, support]) => ({
            product: productName,
            reason: ['Frequently purchased item'],
            confidence: 0.3, // Lower confidence for fallback
            support,
            score: 0.2, // Lowest score
            ruleCount: 1,
            lift: 1.0,
          }));

        console.log('🔄 Frequency-based fallback recommendations:', fallbackRecommendations.length);
        setRecommendations(fallbackRecommendations);
      }
    } else {
      setRecommendations(recommendationsList);
    }
  }, [cart, rules, product]);

  const addToCart = (productToAdd: Product, qty: number = 1) => {
    setCart((prevCart) => {
      const existingItem = prevCart.find((item) => item.id === productToAdd.id);
      if (existingItem) {
        return prevCart.map((item) =>
          item.id === productToAdd.id
            ? { ...item, quantity: item.quantity + qty }
            : item
        );
      }
      return [...prevCart, { ...productToAdd, quantity: qty }];
    });

    const totalItems = cart.reduce((sum, item) => sum + item.quantity, 0) + qty;
    const totalValue = (cart.reduce((sum, item) => sum + item.price * item.quantity, 0) + productToAdd.price * qty).toFixed(2);

    toast.success(`${productToAdd.name} added to cart!`, {
      description: `${qty} ${qty === 1 ? 'item' : 'items'} added • Cart: ${totalItems} items • ₹${totalValue}`,
      action: {
        label: "View Cart",
        onClick: () => navigate('/cart'),
      },
    });
  };

  const increaseQuantity = (productId: number) => {
    setCart((prevCart) =>
      prevCart.map((item) =>
        item.id === productId
          ? { ...item, quantity: item.quantity + 1 }
          : item
      )
    );
  };

  const decreaseQuantity = (productId: number) => {
    setCart((prevCart) => {
      const existingItem = prevCart.find((item) => item.id === productId);
      if (existingItem && existingItem.quantity > 1) {
        return prevCart.map((item) =>
          item.id === productId
            ? { ...item, quantity: item.quantity - 1 }
            : item
        );
      }
      return prevCart.filter((item) => item.id !== productId);
    });
  };

  if (!product) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center p-4">
        <NotFoundErrorState onGoHome={() => navigate('/')} />
      </div>
    );
  }

  const cartItem = cart.find(item => item.id === product.id);
  const isInCart = !!cartItem;
  const isInWishlist = wishlist.some(item => item.id === product.id);

  const toggleWishlist = () => {
    if (isInWishlist) {
      setWishlist(prev => prev.filter(item => item.id !== product.id));
      toast.success(`${product.name} removed from wishlist!`);
    } else {
      setWishlist(prev => [...prev, { ...product, addedAt: new Date() }]);
      toast.success(`${product.name} added to wishlist!`);
    }
  };

  const shareProduct = async (platform: string) => {
    const productUrl = window.location.href;
    const productTitle = `${product.name} - SmartMart`;
    const productDescription = `Check out this ${product.category.toLowerCase()}: ${product.name} for ₹${product.price.toFixed(2)}`;

    try {
      if (platform === 'copy') {
        await navigator.clipboard.writeText(productUrl);
        toast.success("Link copied to clipboard!", {
          description: "Share this link with your friends",
        });
        return;
      }

      // Try Web Share API first (mobile-friendly)
      if (navigator.share && platform === 'native') {
        await navigator.share({
          title: productTitle,
          text: productDescription,
          url: productUrl,
        });
        toast.success("Shared successfully!");
        return;
      }

      // Fallback to URL construction for specific platforms
      let shareUrl = '';

      switch (platform) {
        case 'facebook':
          shareUrl = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(productUrl)}&quote=${encodeURIComponent(productDescription)}`;
          break;
        case 'twitter':
          shareUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(productDescription)}&url=${encodeURIComponent(productUrl)}`;
          break;
        case 'instagram':
          // Instagram doesn't support direct sharing via URL, show message
          toast.info("Instagram sharing", {
            description: "Copy the link and share manually in Instagram",
          });
          await navigator.clipboard.writeText(productUrl);
          return;
        default:
          throw new Error('Unsupported platform');
      }

      // Open share URL in new window
      window.open(shareUrl, '_blank', 'width=600,height=400');
      toast.success(`Opening ${platform}...`);

    } catch (error) {
      console.error('Sharing failed:', error);

      // Fallback: copy to clipboard
      try {
        await navigator.clipboard.writeText(productUrl);
        toast.success("Link copied to clipboard", {
          description: "Sharing failed, but you can paste the link manually",
        });
      } catch (clipboardError) {
        toast.error("Sharing failed", {
          description: "Please copy the URL manually",
        });
      }
    }
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border bg-card sticky top-0 z-10 shadow-sm">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Button variant="ghost" size="sm" onClick={() => navigate('/')}>
                <ArrowLeft className="h-4 w-4 mr-2" />
                Back
              </Button>
              <div>
                <h1 className="text-2xl font-bold text-foreground">SmartMart</h1>
                <p className="text-sm text-muted-foreground">
                  Product Details
                </p>
              </div>
            </div>
            <div className="flex items-center gap-4">
              <Button variant="outline" size="sm" onClick={() => navigate('/')}>
                Continue Shopping
              </Button>
              <button
                onClick={() => navigate('/cart')}
                className="flex items-center gap-2 hover:bg-accent rounded p-1 transition-colors"
              >
                <ShoppingCart className="h-5 w-5 text-muted-foreground" />
                {cart.length > 0 && (
                  <Badge className="bg-cart-badge text-white">
                    {cart.reduce((sum, item) => sum + item.quantity, 0)}
                  </Badge>
                )}
              </button>
            </div>
          </div>
        </div>
      </header>

      <div className="container mx-auto px-4 py-8">
        <div className="space-y-6">
          {/* Product Details */}
          <div className="space-y-6">
            {/* Breadcrumb */}
            <nav className="text-sm text-muted-foreground">
              <span>Home</span> / <span>{product.category}</span> / <span className="text-foreground font-medium">{product.name}</span>
            </nav>

            {/* Product Info */}
            <Card className="p-8">
              <div className="grid lg:grid-cols-2 gap-8">
                {/* Product Image Gallery */}
                <div className="space-y-4">
                  <div className="aspect-square bg-gradient-to-br from-primary/10 to-accent/10 rounded-2xl p-8 border-2 border-primary/20 flex items-center justify-center">
                    <div className="text-9xl">{product.emoji}</div>
                  </div>
                  <Badge variant="secondary" className="text-lg px-4 py-2 block text-center">
                    {product.category}
                  </Badge>
                  {/* Image Gallery Thumbnails */}
                  <div className="flex justify-center gap-2">
                    {product.imageUrls.map((url, idx) => (
                      <button
                        key={idx}
                        className={`w-16 h-16 rounded-lg border-2 flex items-center justify-center text-2xl ${
                          idx === 0 ? 'border-primary' : 'border-muted opacity-50'
                        }`}
                        aria-label={`View image ${idx + 1}`}
                      >
                        {product.emoji}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Product Details */}
                <div className="space-y-6">
                  <div>
                    <div className="flex items-start justify-between mb-2">
                      <h1 className="text-3xl font-bold text-foreground">
                        {product.name}
                      </h1>
                      <Badge variant="outline" className="ml-4">
                        {product.brand}
                      </Badge>
                    </div>
                    <div className="flex items-center gap-2 mb-4">
                      <div className="flex">
                        {[...Array(5)].map((_, i) => (
                          <Star
                            key={i}
                            className={`h-4 w-4 ${
                              i < Math.floor(product.rating)
                                ? 'fill-yellow-400 text-yellow-400'
                                : i < product.rating
                                ? 'fill-yellow-400/50 text-yellow-400'
                                : 'text-muted-foreground'
                            }`}
                          />
                        ))}
                      </div>
                      <span className="text-sm text-muted-foreground">
                        ({product.rating}) • {product.reviewCount} reviews
                      </span>
                    </div>
                    {/* Availability Status */}
                    <div className="flex items-center gap-2 mb-4">
                      <Package className="h-4 w-4" />
                      <Badge
                        variant={
                          product.availability === 'in_stock'
                            ? 'default'
                            : product.availability === 'limited'
                            ? 'secondary'
                            : 'destructive'
                        }
                      >
                        {product.availability === 'in_stock'
                          ? 'In Stock'
                          : product.availability === 'limited'
                          ? 'Limited Stock'
                          : 'Out of Stock'}
                      </Badge>
                    </div>
                  </div>

                  <div className="text-4xl font-bold text-primary">
                    ₹{product.price.toFixed(2)}
                  </div>

                  {/* Product Description */}
                  <div className="space-y-2">
                    <h3 className="font-semibold text-foreground">Description</h3>
                    <p className="text-muted-foreground leading-relaxed">
                      {product.description}
                    </p>
                  </div>

                  {/* Quantity Selector */}
                  <div className="space-y-4">
                    <div className="flex items-center gap-4">
                      <span className="font-medium">Quantity:</span>
                      <div className="flex items-center gap-2">
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => setQuantity(Math.max(1, quantity - 1))}
                          disabled={quantity <= 1}
                          aria-label="Decrease quantity"
                        >
                          <Minus className="h-4 w-4" />
                        </Button>
                        <span className="w-12 text-center font-semibold" aria-label={`Quantity: ${quantity}`}>
                          {quantity}
                        </span>
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => setQuantity(quantity + 1)}
                          disabled={product.availability === 'out_of_stock'}
                          aria-label="Increase quantity"
                        >
                          <Plus className="h-4 w-4" />
                        </Button>
                      </div>
                    </div>

                    {/* Action Buttons */}
                    <div className="flex gap-3">
                      <Button
                        size="lg"
                        className="flex-1 text-lg py-6"
                        onClick={() => addToCart(product, quantity)}
                        disabled={product.availability === 'out_of_stock'}
                      >
                        <ShoppingCart className="h-5 w-5 mr-2" />
                        {product.availability === 'out_of_stock'
                          ? 'Out of Stock'
                          : isInCart
                          ? `Add ${quantity} More`
                          : `Add ${quantity} to Cart`}
                      </Button>
                      <Button
                        size="lg"
                        variant={isInWishlist ? "default" : "outline"}
                        onClick={toggleWishlist}
                        className="px-6"
                        aria-label={isInWishlist ? "Remove from wishlist" : "Add to wishlist"}
                      >
                        <Heart className={`h-5 w-5 ${isInWishlist ? 'fill-current' : ''}`} />
                      </Button>
                    </div>

                    {isInCart && (
                      <p className="text-sm text-muted-foreground text-center">
                        You have {cartItem.quantity} in your cart
                      </p>
                    )}
                  </div>

                  {/* Features */}
                  <div className="grid grid-cols-3 gap-4 pt-6 border-t">
                    <div className="text-center">
                      <Truck className="h-8 w-8 mx-auto mb-2 text-green-600" />
                      <p className="text-sm font-medium">Free Delivery</p>
                      <p className="text-xs text-muted-foreground">On orders over ₹500</p>
                    </div>
                    <div className="text-center">
                      <Shield className="h-8 w-8 mx-auto mb-2 text-blue-600" />
                      <p className="text-sm font-medium">Quality Assured</p>
                      <p className="text-xs text-muted-foreground">Fresh & authentic</p>
                    </div>
                    <div className="text-center">
                      <RotateCcw className="h-8 w-8 mx-auto mb-2 text-orange-600" />
                      <p className="text-sm font-medium">Easy Returns</p>
                      <p className="text-xs text-muted-foreground">30-day policy</p>
                    </div>
                  </div>
                </div>
              </div>
            </Card>

            {/* Enhanced Recommendations - Moved Up for Better Visibility */}
            {recommendations.length > 0 && (
              <Card className="p-6 border-recommendation-border bg-recommendation animate-in fade-in slide-in-from-bottom-4 duration-500">
                <div className="flex items-center gap-2 mb-6">
                  <Sparkles className="h-5 w-5 text-accent-foreground" />
                  <h2 className="text-xl font-bold text-accent-foreground">
                    Recommended for You
                  </h2>
                </div>
                <p className="text-sm text-accent-foreground/80 mb-4">
                  Personalized recommendations powered by Apriori algorithm analysis
                </p>
                <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
                  {recommendations.map((rec, idx) => {
                    const recProduct = products.find((p) => p.name === rec.product);
                    if (!recProduct) return null;
                    return (
                      <Card
                        key={idx}
                        className="p-4 hover:shadow-md transition-all cursor-pointer border-recommendation-border group bg-background/50 backdrop-blur-sm"
                        onClick={() => navigate(`/product/${recProduct.id}`)}
                      >
                        <div className="text-center mb-3">
                          <div className="text-3xl mb-2 group-hover:scale-110 transition-transform duration-300">{recProduct.emoji}</div>
                          <div className="flex justify-center gap-1 mb-2">
                            <Badge variant="secondary" className="text-xs">
                              {(rec.confidence * 100).toFixed(0)}% confidence
                            </Badge>
                            {rec.score && rec.score > 0.5 && (
                              <Badge variant="default" className="text-xs bg-green-100 text-green-800 hover:bg-green-200">
                                High match
                              </Badge>
                            )}
                          </div>
                        </div>
                        <div className="text-center mb-3">
                          <h4 className="font-semibold text-sm mb-1">{recProduct.name}</h4>
                          <p className="text-primary font-bold text-sm">
                            ₹{recProduct.price.toFixed(2)}
                          </p>
                          <div className="flex items-center justify-center gap-1 mt-1">
                            {[...Array(5)].map((_, i) => (
                              <Star
                                key={i}
                                className={`h-3 w-3 ${
                                  i < Math.floor(recProduct.rating)
                                    ? 'fill-yellow-400 text-yellow-400'
                                    : 'text-muted-foreground'
                                }`}
                              />
                            ))}
                            <span className="text-xs text-muted-foreground ml-1">
                              ({recProduct.rating})
                            </span>
                          </div>
                        </div>
                        <div className="text-xs text-accent-foreground/70 space-y-1">
                          <div className="font-medium mb-2">Why recommended:</div>
                          {rec.reason.slice(0, 2).map((reason, rIdx) => (
                            <div key={rIdx} className="truncate" title={reason}>
                              • {reason}
                            </div>
                          ))}
                          {rec.reason.length > 2 && (
                            <div className="text-accent-foreground/50">
                              +{rec.reason.length - 2} more reasons
                            </div>
                          )}
                        </div>
                        <div className="mt-3 pt-3 border-t border-accent-foreground/20">
                          <div className="grid grid-cols-3 gap-1 text-xs text-accent-foreground/60">
                            <div className="text-center">
                              <div className="font-medium">{(rec.support * 100).toFixed(1)}%</div>
                              <div>Support</div>
                            </div>
                            <div className="text-center">
                              <div className="font-medium">{(rec.lift || 1).toFixed(1)}x</div>
                              <div>Lift</div>
                            </div>
                            <div className="text-center">
                              <div className="font-medium">{rec.ruleCount}</div>
                              <div>Rules</div>
                            </div>
                          </div>
                        </div>
                      </Card>
                    );
                  })}
                </div>
              </Card>
            )}

            {/* Tabs for Details, Reviews, and Insights */}
            <Tabs defaultValue="specs" className="w-full">
              <TabsList className="grid w-full grid-cols-3 lg:w-[400px]">
                <TabsTrigger value="specs">Specifications</TabsTrigger>
                <TabsTrigger value="reviews">Reviews</TabsTrigger>
                <TabsTrigger value="insights">AI Insights</TabsTrigger>
              </TabsList>
              
              <TabsContent value="specs" className="mt-6">
                <Card className="p-6">
                  <h3 className="text-xl font-bold text-foreground mb-4">Product Specifications</h3>
                  <div className="grid md:grid-cols-2 gap-6">
                    <div className="space-y-3">
                      <div className="flex justify-between py-2 border-b border-border">
                        <span className="text-muted-foreground">Brand</span>
                        <span className="font-medium">{product.brand}</span>
                      </div>
                      <div className="flex justify-between py-2 border-b border-border">
                        <span className="text-muted-foreground">Category</span>
                        <span className="font-medium">{product.category}</span>
                      </div>
                      <div className="flex justify-between py-2 border-b border-border">
                        <span className="text-muted-foreground">SKU</span>
                        <span className="font-medium font-mono text-sm">{product.sku}</span>
                      </div>
                      <div className="flex justify-between py-2 border-b border-border">
                        <span className="text-muted-foreground">Price</span>
                        <span className="font-medium text-primary">₹{product.price.toFixed(2)}</span>
                      </div>
                      <div className="flex justify-between py-2 border-b border-border">
                        <span className="text-muted-foreground">Availability</span>
                        <Badge variant={
                          product.availability === 'in_stock' ? "default" :
                          product.availability === 'limited' ? "secondary" : "destructive"
                        }>
                          {product.availability === 'in_stock' ? "In Stock" :
                           product.availability === 'limited' ? "Limited Stock" : "Out of Stock"}
                        </Badge>
                      </div>
                    </div>
                    <div className="space-y-3">
                      <div className="flex justify-between py-2 border-b border-border">
                        <span className="text-muted-foreground">Weight</span>
                        <span className="font-medium">{product.weight.value}{product.weight.unit}</span>
                      </div>
                      <div className="flex justify-between py-2 border-b border-border">
                        <span className="text-muted-foreground">Dimensions</span>
                        <span className="font-medium text-sm">
                          {product.dimensions.length} × {product.dimensions.width} × {product.dimensions.height} {product.dimensions.unit}
                        </span>
                      </div>
                      <div className="flex justify-between py-2 border-b border-border">
                        <span className="text-muted-foreground">Origin</span>
                        <span className="font-medium">{product.specifications.Origin || 'India'}</span>
                      </div>
                      <div className="flex justify-between py-2 border-b border-border">
                        <span className="text-muted-foreground">Storage</span>
                        <span className="font-medium">{product.specifications.Storage || 'Cool, dry place'}</span>
                      </div>
                      <div className="flex justify-between py-2 border-b border-border">
                        <span className="text-muted-foreground">Shelf Life</span>
                        <span className="font-medium">{product.specifications['Shelf Life'] || '12 months'}</span>
                      </div>
                    </div>
                  </div>

                  {/* Additional Specifications */}
                  <div className="mt-6 pt-6 border-t border-border">
                    <h4 className="font-semibold text-foreground mb-3">Additional Details</h4>
                    <div className="grid md:grid-cols-2 gap-4">
                      {Object.entries(product.specifications).map(([key, value]) => (
                        key !== 'Origin' && key !== 'Storage' && key !== 'Shelf Life' && (
                          <div key={key} className="flex justify-between py-1">
                            <span className="text-muted-foreground text-sm">{key}</span>
                            <span className="font-medium text-sm">{value}</span>
                          </div>
                        )
                      ))}
                    </div>
                  </div>

                  {/* Tags */}
                  <div className="mt-6 pt-6 border-t border-border">
                    <h4 className="font-semibold text-foreground mb-3">Tags</h4>
                    <div className="flex flex-wrap gap-2">
                      {product.tags.map((tag, idx) => (
                        <Badge key={idx} variant="outline" className="text-xs">
                          {tag}
                        </Badge>
                      ))}
                    </div>
                  </div>
                </Card>
              </TabsContent>

              <TabsContent value="reviews" className="mt-6">
                <Card className="p-6">
                  <div className="flex items-center justify-between mb-6">
                    <h3 className="text-xl font-bold text-foreground">Customer Reviews</h3>
                    <Button variant="outline" size="sm">
                      Write a Review
                    </Button>
                  </div>

                  {/* Overall Rating Summary */}
                  <div className="flex flex-col lg:flex-row items-start lg:items-center gap-6 mb-6 p-4 bg-muted/50 rounded-lg">
                    <div className="text-center">
                      <div className="text-4xl font-bold text-primary mb-2">{product.rating.toFixed(1)}</div>
                      <div className="flex justify-center mb-2">
                        {[...Array(5)].map((_, i) => (
                          <Star key={i} className={`h-5 w-5 ${i < Math.floor(product.rating) ? 'fill-yellow-400 text-yellow-400' : 'text-muted-foreground'}`} />
                        ))}
                      </div>
                      <div className="text-sm text-muted-foreground">{product.reviewCount} reviews</div>
                    </div>
                    <Separator orientation="vertical" className="hidden lg:block h-20" />
                    <div className="flex-1 w-full lg:w-auto">
                      <div className="space-y-2">
                        {[5, 4, 3, 2, 1].map((rating) => {
                          const count = Math.round((product.reviewCount * (rating === 5 ? 0.6 : rating === 4 ? 0.25 : rating === 3 ? 0.1 : rating === 2 ? 0.03 : 0.02)));
                          const percentage = (count / product.reviewCount) * 100;
                          return (
                            <div key={rating} className="flex items-center gap-3 text-sm">
                              <span className="w-6 text-center">{rating}★</span>
                              <Progress value={percentage} className="flex-1 h-2" />
                              <span className="w-8 text-muted-foreground text-right">{count}</span>
                            </div>
                          );
                        })}
                      </div>
                    </div>
                  </div>

                  {/* Review Filters and Sorting */}
                  <div className="flex flex-col sm:flex-row gap-4 mb-6">
                    <div className="flex-1">
                      <select className="w-full px-3 py-2 border border-border rounded-md text-sm bg-background">
                        <option value="newest">Newest First</option>
                        <option value="oldest">Oldest First</option>
                        <option value="highest">Highest Rated</option>
                        <option value="lowest">Lowest Rated</option>
                        <option value="helpful">Most Helpful</option>
                      </select>
                    </div>
                    <div className="flex gap-2">
                      <Button variant="outline" size="sm">All Stars</Button>
                      <Button variant="outline" size="sm">5 Stars</Button>
                      <Button variant="outline" size="sm">4 Stars</Button>
                      <Button variant="outline" size="sm">3 Stars</Button>
                      <Button variant="outline" size="sm">2 Stars</Button>
                      <Button variant="outline" size="sm">1 Star</Button>
                    </div>
                  </div>

                  {/* Individual Reviews */}
                  <div className="space-y-6">
                    {[
                      { name: "Rajesh Kumar", rating: 5, date: "2 days ago", verified: true, helpful: 12, comment: "Excellent quality product! Exactly as described. Fast delivery and great packaging. The " + product.category.toLowerCase() + " exceeded my expectations in terms of freshness and taste." },
                      { name: "Priya Sharma", rating: 4, date: "1 week ago", verified: true, helpful: 8, comment: "Good product overall. Minor issues with packaging but the item itself is perfect. The " + product.name.toLowerCase() + " from " + product.brand + " is exactly what I was looking for." },
                      { name: "Amit Patel", rating: 5, date: "2 weeks ago", verified: false, helpful: 15, comment: "Highly recommend! Will definitely buy again. Great value for money. The quality and freshness of this " + product.category.toLowerCase() + " is outstanding." },
                      { name: "Sneha Gupta", rating: 4, date: "3 weeks ago", verified: true, helpful: 6, comment: "Very satisfied with the purchase. The " + product.name.toLowerCase() + " arrived in perfect condition and the taste is amazing. Would recommend to friends and family." },
                      { name: "Vikram Singh", rating: 3, date: "1 month ago", verified: true, helpful: 4, comment: "Decent product. Met my expectations but nothing extraordinary. The packaging could be better but the quality of the " + product.category.toLowerCase() + " itself is good." },
                      { name: "Kavita Reddy", rating: 5, date: "6 weeks ago", verified: false, helpful: 9, comment: "Absolutely love this! The best " + product.category.toLowerCase() + " I've tried. Fresh, flavorful, and excellent value. " + product.brand + " never disappoints." }
                    ].map((review, idx) => (
                      <div key={idx} className="border-b border-border pb-6 last:border-b-0">
                        <div className="flex items-start justify-between mb-3">
                          <div className="flex items-center gap-3">
                            <div className="w-8 h-8 bg-primary/10 rounded-full flex items-center justify-center text-sm font-medium">
                              {review.name.split(' ').map(n => n[0]).join('')}
                            </div>
                            <div>
                              <div className="flex items-center gap-2">
                                <span className="font-medium">{review.name}</span>
                                {review.verified && (
                                  <Badge variant="secondary" className="text-xs">Verified Purchase</Badge>
                                )}
                              </div>
                              <div className="flex items-center gap-2 mt-1">
                                <div className="flex">
                                  {[...Array(5)].map((_, i) => (
                                    <Star key={i} className={`h-3 w-3 ${i < review.rating ? 'fill-yellow-400 text-yellow-400' : 'text-muted-foreground'}`} />
                                  ))}
                                </div>
                                <span className="text-sm text-muted-foreground">{review.date}</span>
                              </div>
                            </div>
                          </div>
                          <Button variant="ghost" size="sm" className="text-muted-foreground hover:text-foreground">
                            👍 Helpful ({review.helpful})
                          </Button>
                        </div>
                        <p className="text-sm text-muted-foreground leading-relaxed">{review.comment}</p>
                      </div>
                    ))}
                  </div>

                  <div className="text-center mt-6">
                    <Button variant="outline">Load More Reviews</Button>
                  </div>
                </Card>
              </TabsContent>

              <TabsContent value="insights" className="mt-6">
                <Card className="p-6">
                  <h3 className="text-xl font-bold text-foreground mb-4 flex items-center gap-2">
                    <Sparkles className="h-5 w-5 text-primary" />
                    Apriori Algorithm Insights
                  </h3>

                  <div className="space-y-6">
                    <div className="bg-muted/50 p-4 rounded-lg">
                      <h4 className="font-semibold text-foreground mb-2">How Recommendations Work</h4>
                      <p className="text-sm text-muted-foreground leading-relaxed">
                        Our recommendation system uses the Apriori algorithm to analyze shopping patterns from {sampleTransactions().length.toLocaleString()} transactions.
                        When customers buy this {product.category.toLowerCase()}, they often purchase related items based on historical data.
                      </p>
                    </div>

                    <div className="grid md:grid-cols-2 gap-6">
                      <div>
                        <h4 className="font-semibold text-foreground mb-3">Algorithm Metrics</h4>
                        <div className="space-y-3">
                          <div className="flex justify-between items-center py-2 border-b border-border">
                            <span className="text-muted-foreground">Total Transactions</span>
                            <span className="font-medium">{sampleTransactions().length.toLocaleString()}</span>
                          </div>
                          <div className="flex justify-between items-center py-2 border-b border-border">
                            <span className="text-muted-foreground">Association Rules</span>
                            <span className="font-medium">{rules.length}</span>
                          </div>
                          <div className="flex justify-between items-center py-2 border-b border-border">
                            <span className="text-muted-foreground">Min Support</span>
                            <span className="font-medium">1.0%</span>
                          </div>
                          <div className="flex justify-between items-center py-2 border-b border-border">
                            <span className="text-muted-foreground">Min Confidence</span>
                            <span className="font-medium">20.0%</span>
                          </div>
                        </div>
                      </div>

                      <div>
                        <h4 className="font-semibold text-foreground mb-3">Recommendation Logic</h4>
                        <div className="space-y-3 text-sm text-muted-foreground">
                          <div className="flex items-start gap-2">
                            <div className="w-2 h-2 bg-primary rounded-full mt-2 flex-shrink-0"></div>
                            <p>Find rules where current product appears in the antecedent (left side)</p>
                          </div>
                          <div className="flex items-start gap-2">
                            <div className="w-2 h-2 bg-primary rounded-full mt-2 flex-shrink-0"></div>
                            <p>Extract consequent items (right side) as potential recommendations</p>
                          </div>
                          <div className="flex items-start gap-2">
                            <div className="w-2 h-2 bg-primary rounded-full mt-2 flex-shrink-0"></div>
                            <p>Rank by confidence, lift, and support metrics</p>
                          </div>
                          <div className="flex items-start gap-2">
                            <div className="w-2 h-2 bg-primary rounded-full mt-2 flex-shrink-0"></div>
                            <p>Filter out items already in cart for personalized results</p>
                          </div>
                        </div>
                      </div>
                    </div>

                    {recommendations.length > 0 && (
                      <div>
                        <h4 className="font-semibold text-foreground mb-3">Active Rules for This Product</h4>
                        <div className="space-y-3">
                          {recommendations.slice(0, 3).map((rec, idx) => {
                            const recProduct = products.find((p) => p.name === rec.product);
                            return (
                              <div key={idx} className="bg-accent/10 p-3 rounded border">
                                <div className="flex items-center justify-between mb-2">
                                  <span className="font-medium text-sm">{recProduct?.name}</span>
                                  <Badge variant="outline" className="text-xs">
                                    {(rec.confidence * 100).toFixed(0)}% confidence
                                  </Badge>
                                </div>
                                <div className="grid grid-cols-3 gap-4 text-xs text-muted-foreground">
                                  <div>
                                    <div className="font-medium text-foreground">{(rec.support * 100).toFixed(1)}%</div>
                                    <div>Support</div>
                                  </div>
                                  <div>
                                    <div className="font-medium text-foreground">{(rec.lift || 1).toFixed(1)}x</div>
                                    <div>Lift</div>
                                  </div>
                                  <div>
                                    <div className="font-medium text-foreground">{rec.ruleCount}</div>
                                    <div>Rules</div>
                                  </div>
                                </div>
                              </div>
                            );
                          })}
                        </div>
                      </div>
                    )}
                  </div>
                </Card>
              </TabsContent>
            </Tabs>

            {/* Social Sharing & Recently Viewed - Moved to bottom */}
            <div className="grid md:grid-cols-2 gap-6">
              {/* Social Sharing */}
              <Card className="p-6">
                <h3 className="text-lg font-bold text-foreground mb-4">Share this product</h3>
                <div className="flex flex-wrap gap-3">
                  <Button
                    variant="outline"
                    size="sm"
                    className="flex items-center gap-2"
                    onClick={() => shareProduct('facebook')}
                  >
                    📘 Facebook
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    className="flex items-center gap-2"
                    onClick={() => shareProduct('twitter')}
                  >
                    🐦 Twitter
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    className="flex items-center gap-2"
                    onClick={() => shareProduct('instagram')}
                  >
                    📷 Instagram
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    className="flex items-center gap-2"
                    onClick={() => shareProduct('copy')}
                  >
                    🔗 Copy Link
                  </Button>
                  {navigator.share && (
                    <Button
                      variant="outline"
                      size="sm"
                      className="flex items-center gap-2"
                      onClick={() => shareProduct('native')}
                    >
                      📱 Share
                    </Button>
                  )}
                </div>
                <p className="text-xs text-muted-foreground mt-3">
                  Share this amazing {product.category.toLowerCase()} with your friends!
                </p>
              </Card>

              {/* Recently Viewed */}
              <Card className="p-6">
                <h3 className="text-xl font-bold text-foreground mb-4">Recently Viewed</h3>
                <div className="grid grid-cols-2 gap-4">
                  {(() => {
                    try {
                      const viewedData = localStorage.getItem('smartmart-recently-viewed');
                      if (viewedData) {
                        const recentlyViewed: Array<{ id: number; name: string; viewedAt: string }> = JSON.parse(viewedData);
                        // Filter out current product and limit to 2 for display in this smaller space
                        const recentProducts = recentlyViewed
                          .filter(item => item.id !== product?.id)
                          .slice(0, 2)
                          .map(item => products.find(p => p.id === item.id))
                          .filter(Boolean) as Product[];

                        return recentProducts.map((recentProduct) => (
                          <Card
                            key={recentProduct.id}
                            className="p-3 hover:shadow-md transition-all cursor-pointer"
                            onClick={() => navigate(`/product/${recentProduct.id}`)}
                          >
                            <div className="text-center mb-2">
                              <div className="text-2xl mb-1">{recentProduct.emoji}</div>
                              <Badge variant="secondary" className="text-[10px] px-1 py-0">
                                {recentProduct.category}
                              </Badge>
                            </div>
                            <div className="text-center">
                              <h4 className="font-semibold text-xs mb-1 line-clamp-1">{recentProduct.name}</h4>
                              <p className="text-primary font-bold text-xs">
                                ₹{recentProduct.price.toFixed(2)}
                              </p>
                            </div>
                          </Card>
                        ));
                      }
                    } catch (error) {
                      console.error('Error loading recently viewed products:', error);
                    }
                    return null;
                  })()}
                </div>
              </Card>
            </div>
          </div>

        </div>
      </div>

      <Footer />
    </div>
  );
};

export default ProductDetail;